-- The home screen's verse rotation: 183 verses, one for each day, cycling.
--
-- Korean is 개역한글판 (대한성서공회), English is the World English Bible (public domain), and
-- Khmer is the 1954 translation (The Bible Society in Cambodia). The verse list and its order
-- come from verses/daily-verses.refs.json; the text was fetched by scripts/fill-verses.mjs and
-- is stored exactly as the publishers print it.
--
-- 00107 seeded one verse per language so the card was never blank. Those three rows are kept
-- in a backup table first, then removed — 시편 27:1 is not in this list, and sort_order 1 is
-- needed by day 1.

CREATE TABLE public.daily_verses_backup_00108 AS
  SELECT * FROM public.daily_verses;

DELETE FROM public.daily_verses;

INSERT INTO public.daily_verses (locale, sort_order, reference, passage) VALUES
  ('ko', 1, '시편 2:8', '내게 구하라 내가 열방을 유업으로 주리니 네 소유가 땅 끝까지 이르리로다'),
  ('ko', 2, '출애굽기 34:6', '여호와께서 그의 앞으로 지나시며 반포하시되 여호와로라 여호와로라 자비롭고 은혜롭고 노하기를 더디하고 인자와 진실이 많은 하나님이로라'),
  ('ko', 3, '여호수아 1:9', '내가 네게 명한 것이 아니냐 마음을 강하게 하고 담대히 하라 두려워 말며 놀라지 말라 네가 어디로 가든지 네 하나님 여호와가 너와 함께 하느니라 하시니라'),
  ('ko', 4, '잠언 3:5', '너는 마음을 다하여 여호와를 의뢰하고 네 명철을 의지하지 말라'),
  ('ko', 5, '요한복음 13:34', '새 계명을 너희에게 주노니 서로 사랑하라 내가 너희를 사랑한것 같이 너희도 서로 사랑하라'),
  ('ko', 6, '미가 6:8', '사람아 주께서 선한 것이 무엇임을 네게 보이셨나니 여호와께서 네게 구하시는 것이 오직 공의를 행하며 인자를 사랑하며 겸손히 네 하나님과 함께 행하는 것이 아니냐'),
  ('ko', 7, '창세기 12:2', '내가 너로 큰 민족을 이루고 네게 복을 주어 네 이름을 창대케 하리니 너는 복의 근원이 될찌라'),
  ('ko', 8, '시편 145:8', '여호와는 은혜로우시며 자비하시며 노하기를 더디하시며 인자하심이 크시도다'),
  ('ko', 9, '신명기 31:8', '여호와 그가 네 앞서 행하시며 너와 함께하사 너를 떠나지 아니하시며 버리지 아니하시리니 너는 두려워 말라 놀라지 말라'),
  ('ko', 10, '잠언 3:6', '너는 범사에 그를 인정하라 그리하면 네 길을 지도하시리라'),
  ('ko', 11, '요한복음 13:35', '너희가 서로 사랑하면 이로써 모든 사람이 너희가 내 제자인줄 알리라'),
  ('ko', 12, '여호수아 24:15', '만일 여호와를 섬기는 것이 너희에게 좋지 않게 보이거든 너희 열조가 강 저편에서 섬기던 신이든지 혹 너희의 거하는 땅 아모리 사람의 신이든지 너희 섬길 자를 오늘날 택하라 오직 나와 내 집은 여호와를 섬기겠노라'),
  ('ko', 13, '창세기 28:15', '내가 너와 함께 있어 네가 어디로 가든지 너를 지키며 너를 이끌어 이 땅으로 돌아오게 할찌라 내가 네게 허락한 것을 다 이루기까지 너를 떠나지 아니하리라 하신지라'),
  ('ko', 14, '시편 145:18', '여호와께서는 자기에게 간구하는 모든 자 곧 진실하게 간구하는 모든 자에게 가까이 하시는도다'),
  ('ko', 15, '시편 23:1', '여호와는 나의 목자시니 내가 부족함이 없으리로다'),
  ('ko', 16, '잠언 16:3', '너의 행사를 여호와께 맡기라 그리하면 너의 경영하는 것이 이루리라'),
  ('ko', 17, '요한복음 15:5', '나는 포도나무요 너희는 가지니 저가 내 안에, 내가 저 안에 있으면 이 사람은 과실을 많이 맺나니 나를 떠나서는 너희가 아무 것도 할 수 없음이라'),
  ('ko', 18, '시편 1:1', '복 있는 사람은 악인의 꾀를 좇지 아니하며 죄인의 길에 서지 아니하며 오만한 자의 자리에 앉지 아니하고'),
  ('ko', 19, '시편 67:2', '주의 도를 땅 위에, 주의 구원을 만방 중에 알리소서'),
  ('ko', 20, '시편 103:8', '여호와는 자비로우시며 은혜로우시며 노하기를 더디 하시며 인자하심이 풍부하시도다'),
  ('ko', 21, '시편 23:4', '내가 사망의 음침한 골짜기로 다닐찌라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다'),
  ('ko', 22, '잠언 16:9', '사람이 마음으로 자기의 길을 계획할지라도 그 걸음을 인도하는 자는 여호와시니라'),
  ('ko', 23, '요한복음 15:12', '내 계명은 곧 내가 너희를 사랑한 것 같이 너희도 서로 사랑하라 하는 이것이니라'),
  ('ko', 24, '시편 119:105', '주의 말씀은 내 발에 등이요 내 길에 빛이니이다'),
  ('ko', 25, '시편 96:3', '그 영광을 열방 중에, 그 기이한 행적을 만민 중에 선포할찌어다'),
  ('ko', 26, '시편 103:13', '아비가 자식을 불쌍히 여김 같이 여호와께서 자기를 경외하는 자를 불쌍히 여기시나니'),
  ('ko', 27, '시편 27:1', '여호와는 나의 빛이요 나의 구원이시니 내가 누구를 두려워하리요 여호와는 내 생명의 능력이시니 내가 누구를 무서워하리요'),
  ('ko', 28, '시편 37:4', '또 여호와를 기뻐하라 저가 네 마음의 소원을 이루어 주시리로다'),
  ('ko', 29, '요한복음 15:13', '사람이 친구를 위하여 자기 목숨을 버리면 이에서 더 큰 사랑이 없나니'),
  ('ko', 30, '시편 119:11', '내가 주께 범죄치 아니하려 하여 주의 말씀을 내 마음에 두었나이다'),
  ('ko', 31, '이사야 6:8', '내가 또 주의 목소리를 들은즉 이르시되 내가 누구를 보내며 누가 우리를 위하여 갈꼬 그 때에 내가 가로되 내가 여기 있나이다 나를 보내소서'),
  ('ko', 32, '시편 100:5', '대저 여호와는 선하시니 그 인자하심이 영원하고 그 성실하심이 대대에 미치리로다'),
  ('ko', 33, '시편 34:18', '여호와는 마음이 상한 자에게 가까이 하시고 중심에 통회하는 자를 구원하시는도다'),
  ('ko', 34, '시편 37:5', '너의 길을 여호와께 맡기라 저를 의지하면 저가 이루시고'),
  ('ko', 35, '고린도전서 13:4', '사랑은 오래 참고 사랑은 온유하며 투기하는 자가 되지 아니하며 사랑은 자랑하지 아니하며 교만하지 아니하며'),
  ('ko', 36, '시편 51:10', '하나님이여 내 속에 정한 마음을 창조하시고 내 안에 정직한 영을 새롭게 하소서'),
  ('ko', 37, '이사야 9:6', '이는 한 아기가 우리에게 났고 한 아들을 우리에게 주신바 되었는데 그 어깨에는 정사를 메었고 그 이름은 기묘자라, 모사라, 전능하신 하나님이라, 영존하시는 아버지라, 평강의 왕이라 할것임이라'),
  ('ko', 38, '시편 136:1', '여호와께 감사하라 그는 선하시며 그 인자하심이 영원함이로다'),
  ('ko', 39, '시편 46:1', '하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라'),
  ('ko', 40, '시편 18:2', '여호와는 나의 반석이시요 나의 요새시요 나를 건지시는 자시요 나의 하나님이시요 나의 피할 바위시요 나의 방패시요 나의 구원의 뿔이시요 나의 산성이시로다'),
  ('ko', 41, '고린도전서 13:13', '그런즉 믿음, 소망, 사랑, 이 세 가지는 항상 있을 것인데 그 중에 제일은 사랑이라'),
  ('ko', 42, '시편 19:14', '나의 반석이시요 나의 구속자이신 여호와여 내 입의 말과 마음의 묵상이 주의 앞에 열납되기를 원하나이다'),
  ('ko', 43, '이사야 43:19', '보라 내가 새 일을 행하리니 이제 나타낼 것이라 너희가 그것을 알지 못하겠느냐 정녕히 내가 광야에 길과 사막에 강을 내리니'),
  ('ko', 44, '시편 90:2', '산이 생기기 전, 땅과 세계도 주께서 조성하시기 전 곧 영원부터 영원까지 주는 하나님이시니이다'),
  ('ko', 45, '시편 46:10', '이르시기를 너희는 가만히 있어 내가 하나님 됨을 알찌어다 내가 열방과 세계 중에서 높임을 받으리라 하시도다'),
  ('ko', 46, '히브리서 11:1', '믿음은 바라는 것들의 실상이요 보지 못하는 것들의 증거니'),
  ('ko', 47, '고린도전서 16:14', '너희 모든 일을 사랑으로 행하라'),
  ('ko', 48, '시편 90:12', '우리에게 우리 날 계수함을 가르치사 지혜의 마음을 얻게 하소서'),
  ('ko', 49, '이사야 49:6', '그가 가라사대 네가 나의 종이 되어 야곱의 지파들을 일으키며 이스라엘 중에 보전된 자를 돌아오게 할 것은 오히려 경한 일이라 내가 또 너로 이방의 빛을 삼아 나의 구원을 베풀어서 땅 끝까지 이르게 하리라'),
  ('ko', 50, '시편 139:1', '여호와여 주께서 나를 감찰하시고 아셨나이다'),
  ('ko', 51, '시편 55:22', '네 짐을 여호와께 맡겨 버리라 너를 붙드시고 의인의 요동함을 영영히 허락지 아니하시리로다'),
  ('ko', 52, '히브리서 11:6', '믿음이 없이는 기쁘시게 못하나니 하나님께 나아가는 자는 반드시 그가 계신 것과 또한 그가 자기를 찾는 자들에게 상 주시는 이심을 믿어야 할찌니라'),
  ('ko', 53, '로마서 12:10', '형제를 사랑하여 서로 우애하고 존경하기를 서로 먼저 하며'),
  ('ko', 54, '시편 118:24', '이 날은 여호와의 정하신 것이라 이 날에 우리가 즐거워하고 기뻐하리로다'),
  ('ko', 55, '이사야 52:7', '좋은 소식을 가져오며 평화를 공포하며 복된 좋은 소식을 가져오며 구원을 공포하며 시온을 향하여 이르기를 네 하나님이 통치하신다 하는 자의 산을 넘는 발이 어찌 그리 아름다운고'),
  ('ko', 56, '시편 139:14', '내가 주께 감사하옴은 나를 지으심이 신묘막측하심이라 주의 행사가 기이함을 내 영혼이 잘 아나이다'),
  ('ko', 57, '시편 56:3', '내가 두려워하는 날에는 주를 의지하리이다'),
  ('ko', 58, '히브리서 12:2', '믿음의 주요 또 온전케 하시는 이인 예수를 바라보자 저는 그 앞에 있는 즐거움을 위하여 십자가를 참으사 부끄러움을 개의치 아니하시더니 하나님 보좌 우편에 앉으셨느니라'),
  ('ko', 59, '로마서 12:15', '즐거워하는 자들로 함께 즐거워하고 우는 자들로 함께 울라'),
  ('ko', 60, '잠언 1:7', '여호와를 경외하는 것이 지식의 근본이어늘 미련한 자는 지혜와 훈계를 멸시하느니라'),
  ('ko', 61, '이사야 60:1', '일어나라 빛을 발하라 이는 네 빛이 이르렀고 여호와의 영광이 네 위에 임하였음이니라'),
  ('ko', 62, '예레미야애가 3:22', '여호와의 자비와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다'),
  ('ko', 63, '시편 62:1', '나의 영혼이 잠잠히 하나님만 바람이여 나의 구원이 그에게서 나는도다'),
  ('ko', 64, '로마서 8:28', '우리가 알거니와 하나님을 사랑하는 자 곧 그 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라'),
  ('ko', 65, '로마서 13:8', '피차 사랑의 빚 외에는 아무에게든지 아무 빚도 지지 말라 남을 사랑하는 자는 율법을 다 이루었느니라'),
  ('ko', 66, '잠언 4:23', '무릇 지킬만한 것보다 더욱 네 마음을 지키라 생명의 근원이 이에서 남이니라'),
  ('ko', 67, '하박국 2:14', '대저 물이 바다를 덮음 같이 여호와의 영광을 인정하는 것이 세상에 가득하리라'),
  ('ko', 68, '이사야 40:28', '너는 알지 못하였느냐 듣지 못하였느냐 영원하신 하나님 여호와, 땅 끝까지 창조하신 자는 피곤치 아니하시며 곤비치 아니하시며 명철이 한이 없으시며'),
  ('ko', 69, '시편 91:1', '지존자의 은밀한 곳에 거하는 자는 전능하신 자의 그늘 아래 거하리로다'),
  ('ko', 70, '로마서 8:31', '그런즉 이 일에 대하여 우리가 무슨 말 하리요 만일 하나님이 우리를 위하시면 누가 우리를 대적하리요'),
  ('ko', 71, '로마서 15:7', '이러므로 그리스도께서 우리를 받아 하나님께 영광을 돌리심과 같이 너희도 서로 받으라'),
  ('ko', 72, '잠언 9:10', '여호와를 경외하는 것이 지혜의 근본이요 거룩하신 자를 아는 것이 명철이니라'),
  ('ko', 73, '스가랴 4:6', '그가 내게 일러 가로되 여호와께서 스룹바벨에게 하신 말씀이 이러하니라 만군의 여호와께서 말씀하시되 이는 힘으로 되지 아니하며 능으로 되지아니하고 오직 나의 신으로 되느니라'),
  ('ko', 74, '이사야 55:8', '여호와의 말씀에 내 생각은 너희 생각과 다르며 내 길은 너희 길과 달라서'),
  ('ko', 75, '시편 121:2', '나의 도움이 천지를 지으신 여호와에게서로다'),
  ('ko', 76, '로마서 8:37', '그러나 이 모든 일에 우리를 사랑하시는 이로 말미암아 우리가 넉넉히 이기느니라'),
  ('ko', 77, '갈라디아서 5:13', '형제들아 너희가 자유를 위하여 부르심을 입었으나 그러나 그 자유로 육체의 기회를 삼지 말고 오직 사랑으로 서로 종노릇하라'),
  ('ko', 78, '잠언 15:1', '유순한 대답은 분노를 쉬게 하여도 과격한 말은 노를 격동하느니라'),
  ('ko', 79, '마태복음 24:14', '이 천국 복음이 모든 민족에게 증거되기 위하여 온 세상에 전파되리니 그제야 끝이 오리라'),
  ('ko', 80, '이사야 6:3', '서로 창화하여 가로되 거룩하다 거룩하다 거룩하다 만군의 여호와여 그 영광이 온 땅에 충만하도다'),
  ('ko', 81, '시편 121:8', '여호와께서 너의 출입을 지금부터 영원까지 지키시리로다'),
  ('ko', 82, '로마서 10:17', '그러므로 믿음은 들음에서 나며 들음은 그리스도의 말씀으로 말미암았느니라'),
  ('ko', 83, '갈라디아서 6:2', '너희가 짐을 서로 지라 그리하여 그리스도의 법을 성취하라'),
  ('ko', 84, '잠언 22:6', '마땅히 행할 길을 아이에게 가르치라 그리하면 늙어도 그것을 떠나지 아니하리라'),
  ('ko', 85, '마태복음 28:19', '그러므로 너희는 가서 모든 족속으로 제자를 삼아 아버지와 아들과 성령의 이름으로 세례를 주고'),
  ('ko', 86, '말라기 3:6', '나 여호와는 변역지 아니하나니 그러므로 야곱의 자손들아 너희가 소멸되지 아니하느니라'),
  ('ko', 87, '시편 147:3', '상심한 자를 고치시며 저희 상처를 싸매시는도다'),
  ('ko', 88, '로마서 1:17', '복음에는 하나님의 의가 나타나서 믿음으로 믿음에 이르게 하나니 기록된바 오직 의인은 믿음으로 말미암아 살리라 함과 같으니라'),
  ('ko', 89, '에베소서 4:2', '모든 겸손과 온유로 하고 오래 참음으로 사랑 가운데서 서로 용납하고'),
  ('ko', 90, '전도서 3:1', '천하에 범사가 기한이 있고 모든 목적이 이룰 때가 있나니'),
  ('ko', 91, '마태복음 28:20', '내가 너희에게 분부한 모든 것을 가르쳐 지키게 하라 볼찌어다 내가 세상 끝날까지 너희와 항상 함께 있으리라 하시니라'),
  ('ko', 92, '요한복음 1:14', '말씀이 육신이 되어 우리 가운데 거하시매 우리가 그 영광을 보니 아버지의 독생자의 영광이요 은혜와 진리가 충만하더라'),
  ('ko', 93, '이사야 40:31', '오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리의 날개치며 올라감 같을 것이요 달음박질하여도 곤비치 아니하겠고 걸어가도 피곤치 아니하리로다'),
  ('ko', 94, '갈라디아서 2:20', '내가 그리스도와 함께 십자가에 못 박혔나니 그런즉 이제는 내가 산 것이 아니요 오직 내 안에 그리스도께서 사신 것이라 이제 내가 육체 가운데 사는 것은 나를 사랑하사 나를 위하여 자기 몸을 버리신 하나님의 아들을 믿는 믿음 안에서 사는 것이라'),
  ('ko', 95, '에베소서 4:32', '서로 인자하게 하며 불쌍히 여기며 서로 용서하기를 하나님이 그리스도 안에서 너희를 용서하심과 같이 하라'),
  ('ko', 96, '전도서 12:13', '일의 결국을 다 들었으니 하나님을 경외하고 그 명령을 지킬찌어다 이것이 사람의 본분이니라'),
  ('ko', 97, '마가복음 16:15', '또 가라사대 너희는 온 천하에 다니며 만민에게 복음을 전파하라'),
  ('ko', 98, '요한복음 3:16', '하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 이는 저를 믿는 자마다 멸망치 않고 영생을 얻게 하려 하심이니라'),
  ('ko', 99, '이사야 41:10', '두려워 말라 내가 너와 함께 함이니라 놀라지 말라 나는 네 하나님이 됨이니라 내가 너를 굳세게 하리라 참으로 너를 도와 주리라 참으로 나의 의로운 오른손으로 너를 붙들리라'),
  ('ko', 100, '에베소서 2:8', '너희가 그 은혜를 인하여 믿음으로 말미암아 구원을 얻었나니 이것이 너희에게서 난 것이 아니요 하나님의 선물이라'),
  ('ko', 101, '골로새서 3:13', '누가 뉘게 혐의가 있거든 서로 용납하여 피차 용서하되 주께서 너희를 용서하신 것과 같이 너희도 그리하고'),
  ('ko', 102, '마태복음 5:14', '너희는 세상의 빛이라 산위에 있는 동네가 숨기우지 못할 것이요'),
  ('ko', 103, '사도행전 1:8', '오직 성령이 너희에게 임하시면 너희가 권능을 받고 예루살렘과 온 유대와 사마리아와 땅끝까지 이르러 내 증인이 되리라 하시니라'),
  ('ko', 104, '요한복음 4:24', '하나님은 영이시니 예배하는 자가 신령과 진정으로 예배할찌니라'),
  ('ko', 105, '이사야 43:2', '네가 물 가운데로 지날 때에 내가 함께할 것이라 강을 건널 때에 물이 너를 침몰치 못할 것이며 네가 불 가운데로 행할 때에 타지도 아니할 것이요 불꽃이 너를 사르지도 못하리니'),
  ('ko', 106, '마가복음 9:23', '예수께서 이르시되 할 수 있거든이 무슨 말이냐 믿는 자에게는 능치 못할 일이 없느니라 하시니'),
  ('ko', 107, '골로새서 3:14', '이 모든 것 위에 사랑을 더하라 이는 온전하게 매는 띠니라'),
  ('ko', 108, '마태복음 5:16', '이같이 너희 빛을 사람 앞에 비취게 하여 저희로 너희 착한 행실을 보고 하늘에 계신 너희 아버지께 영광을 돌리게 하라'),
  ('ko', 109, '사도행전 20:24', '나의 달려갈 길과 주 예수께 받은 사명 곧 하나님의 은혜의 복음 증거하는 일을 마치려 함에는 나의 생명을 조금도 귀한 것으로 여기지 아니하노라'),
  ('ko', 110, '요한복음 10:11', '나는 선한 목자라 선한 목자는 양들을 위하여 목숨을 버리거니와'),
  ('ko', 111, '예레미야 29:11', '나 여호와가 말하노라 너희를 향한 나의 생각은 내가 아나니 재앙이 아니라 곧 평안이요 너희 장래에 소망을 주려하는 생각이라'),
  ('ko', 112, '마가복음 11:24', '그러므로 내가 너희에게 말하노니 무엇이든지 기도하고 구하는 것은 받은 줄로 믿으라 그리하면 너희에게 그대로 되리라'),
  ('ko', 113, '빌립보서 2:3', '아무 일에든지 다툼이나 허영으로 하지 말고 오직 겸손한 마음으로 각각 자기보다 남을 낫게 여기고'),
  ('ko', 114, '마태복음 7:12', '그러므로 무엇이든지 남에게 대접을 받고자 하는대로 너희도 남을 대접하라 이것이 율법이요 선지자니라'),
  ('ko', 115, '로마서 1:16', '내가 복음을 부끄러워하지 아니하노니 이 복음은 모든 믿는 자에게 구원을 주시는 하나님의 능력이 됨이라 첫째는 유대인에게요 또한 헬라인에게로다'),
  ('ko', 116, '요한복음 11:25', '예수께서 가라사대 나는 부활이요 생명이니 나를 믿는 자는 죽어도 살겠고'),
  ('ko', 117, '마태복음 11:28', '수고하고 무거운 짐진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라'),
  ('ko', 118, '마태복음 6:33', '너희는 먼저 그의 나라와 그의 의를 구하라 그리하면 이 모든 것을 너희에게 더하시리라'),
  ('ko', 119, '빌립보서 2:4', '각각 자기 일을 돌아볼 뿐더러 또한 각각 다른 사람들의 일을 돌아보아 나의 기쁨을 충만케 하라'),
  ('ko', 120, '마태복음 22:37', '예수께서 가라사대 네 마음을 다하고 목숨을 다하고 뜻을 다하여 주 너의 하나님을 사랑하라 하셨으니'),
  ('ko', 121, '로마서 10:15', '보내심을 받지 아니하였으면 어찌 전파하리요 기록된바 아름답도다 좋은 소식을 전하는 자들의 발이여 함과 같으니라'),
  ('ko', 122, '요한복음 14:6', '예수께서 가라사대 내가 곧 길이요 진리요 생명이니 나로 말미암지 않고는 아버지께로 올 자가 없느니라'),
  ('ko', 123, '요한복음 14:27', '평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라 내가 너희에게 주는 것은 세상이 주는 것 같지 아니하니라 너희는 마음에 근심도 말고 두려워하지도 말라'),
  ('ko', 124, '마태복음 6:34', '그러므로 내일 일을 위하여 염려하지 말라 내일 일은 내일 염려할 것이요 한 날 괴로움은 그 날에 족하니라'),
  ('ko', 125, '히브리서 10:24', '서로 돌아보아 사랑과 선행을 격려하며'),
  ('ko', 126, '누가복음 9:23', '또 무리에게 이르시되 아무든지 나를 따라 오려거든 자기를 부인하고 날마다 제 십자가를 지고 나를 좇을 것이니라'),
  ('ko', 127, '로마서 15:13', '소망의 하나님이 모든 기쁨과 평강을 믿음 안에서 너희에게 충만케 하사 성령의 능력으로 소망이 넘치게 하시기를 원하노라'),
  ('ko', 128, '로마서 5:8', '우리가 아직 죄인 되었을 때에 그리스도께서 우리를 위하여 죽으심으로 하나님께서 우리에게 대한 자기의 사랑을 확증하셨느니라'),
  ('ko', 129, '요한복음 16:33', '이것을 너희에게 이름은 너희로 내 안에서 평안을 누리게 하려함이라 세상에서는 너희가 환난을 당하나 담대하라 내가 세상을 이기었노라 하시니라'),
  ('ko', 130, '마태복음 7:7', '구하라 그러면 너희에게 주실 것이요 찾으라 그러면 찾을 것이요 문을 두드리라 그러면 너희에게 열릴 것이니'),
  ('ko', 131, '히브리서 10:25', '모이기를 폐하는 어떤 사람들의 습관과 같이 하지 말고 오직 권하여 그날이 가까움을 볼수록 더욱 그리하자'),
  ('ko', 132, '로마서 12:1', '그러므로 형제들아 내가 하나님의 모든 자비하심으로 너희를 권하노니 너희 몸을 하나님이 기뻐하시는 거룩한 산 제사로 드리라 이는 너희의 드릴 영적 예배니라'),
  ('ko', 133, '고린도후서 4:16', '그러므로 우리가 낙심하지 아니하노니 겉사람은 후패하나 우리의 속은 날로 새롭도다'),
  ('ko', 134, '로마서 11:36', '이는 만물이 주에게서 나오고 주로 말미암고 주에게로 돌아감이라 영광이 그에게 세세에 있으리로다 아멘'),
  ('ko', 135, '고린도후서 12:9', '내게 이르시기를 내 은혜가 네게 족하도다 이는 내 능력이 약한데서 온전하여짐이라 하신지라 이러므로 도리어 크게 기뻐함으로 나의 여러 약한 것들에 대하여 자랑하리니 이는 그리스도의 능력으로 내게 머물게 하려함이라'),
  ('ko', 136, '빌립보서 4:13', '내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라'),
  ('ko', 137, '베드로전서 4:8', '무엇보다도 열심으로 서로 사랑할찌니 사랑은 허다한 죄를 덮느니라'),
  ('ko', 138, '로마서 12:2', '너희는 이 세대를 본받지 말고 오직 마음을 새롭게 함으로 변화를 받아 하나님의 선하시고 기뻐하시고 온전하신 뜻이 무엇인지 분별하도록 하라'),
  ('ko', 139, '고린도후서 4:18', '우리의 돌아보는 것은 보이는 것이 아니요 보이지 않는 것이니 보이는 것은 잠간이요 보이지 않는 것은 영원함이니라'),
  ('ko', 140, '요한일서 4:8', '사랑하지 아니하는 자는 하나님을 알지 못하나니 이는 하나님은 사랑이심이라'),
  ('ko', 141, '베드로전서 5:7', '너희 염려를 다 주께 맡겨 버리라 이는 저가 너희를 권고하심이니라'),
  ('ko', 142, '빌립보서 1:6', '너희 속에 착한 일을 시작하신 이가 그리스도 예수의 날까지 이루실 줄을 우리가 확신하노라'),
  ('ko', 143, '요한일서 3:18', '자녀들아 우리가 말과 혀로만 사랑하지 말고 오직 행함과 진실함으로 하자'),
  ('ko', 144, '로마서 12:12', '소망 중에 즐거워하며 환난 중에 참으며 기도에 항상 힘쓰며'),
  ('ko', 145, '고린도후서 5:20', '이러므로 우리가 그리스도를 대신하여 사신이 되어 하나님이 우리로 너희를 권면하시는 것 같이 그리스도를 대신하여 간구하노니 너희는 하나님과 화목하라'),
  ('ko', 146, '야고보서 1:17', '각양 좋은 은사와 온전한 선물이 다 위로부터 빛들의 아버지께로서 내려오나니 그는 변함도 없으시고 회전하는 그림자도 없으시니라'),
  ('ko', 147, '빌립보서 4:6', '아무 것도 염려하지 말고 오직 모든 일에 기도와 간구로, 너희 구할 것을 감사함으로 하나님께 아뢰라'),
  ('ko', 148, '고린도후서 5:7', '이는 우리가 믿음으로 행하고 보는 것으로 하지 아니함이로라'),
  ('ko', 149, '요한일서 4:7', '사랑하는 자들아 우리가 서로 사랑하자 사랑은 하나님께 속한것이니 사랑하는 자마다 하나님께로 나서 하나님을 알고'),
  ('ko', 150, '로마서 12:21', '악에게 지지 말고 선으로 악을 이기라'),
  ('ko', 151, '에베소서 3:20', '우리 가운데서 역사하시는 능력대로 우리의 온갖 구하는 것이나 생각하는 것에 더 넘치도록 능히 하실 이에게'),
  ('ko', 152, '히브리서 13:8', '예수 그리스도는 어제나 오늘이나 영원토록 동일하시니라'),
  ('ko', 153, '요한계시록 21:4', '모든 눈물을 그 눈에서 씻기시매 다시 사망이 없고 애통하는 것이나 곡하는 것이나 아픈 것이 다시 있지 아니하리니 처음 것들이 다 지나갔음이러라'),
  ('ko', 154, '요한복음 20:29', '예수께서 가라사대 너는 나를 본 고로 믿느냐 보지못하고 믿는 자들은 복되도다 하시니라'),
  ('ko', 155, '요한일서 4:19', '우리가 사랑함은 그가 먼저 우리를 사랑하셨음이라'),
  ('ko', 156, '고린도전서 10:31', '그런즉 너희가 먹든지 마시든지 무엇을 하든지 다 하나님의 영광을 위하여 하라'),
  ('ko', 157, '빌립보서 3:14', '푯대를 향하여 그리스도 예수 안에서 하나님이 위에서 부르신 부름의 상을 위하여 좇아가노라'),
  ('ko', 158, '요한계시록 1:8', '주 하나님이 가라사대 나는 알파와 오메가라 이제도 있고 전에도 있었고 장차 올 자요 전능한 자라 하시더라'),
  ('ko', 159, '야고보서 1:5', '너희 중에 누구든지 지혜가 부족하거든 모든 사람에게 후히 주시고 꾸짖지 아니하시는 하나님께 구하라 그리하면 주시리라'),
  ('ko', 160, '전도서 4:12', '한 사람이면 패하겠거니와 두 사람이면 능히 당하나니 삼겹 줄은 쉽게 끊어지지 아니하느니라'),
  ('ko', 161, '고린도후서 5:17', '그런즉 누구든지 그리스도 안에 있으면 새로운 피조물이라 이전 것은 지나갔으니 보라 새것이 되었도다'),
  ('ko', 162, '빌립보서 3:20', '오직 우리의 시민권은 하늘에 있는지라 거기로서 구원하는 자 곧 주 예수 그리스도를 기다리노니'),
  ('ko', 163, '시편 133:1', '형제가 연합하여 동거함이 어찌 그리 선하고 아름다운고'),
  ('ko', 164, '갈라디아서 6:9', '우리가 선을 행하되 낙심하지 말찌니 피곤하지 아니하면 때가 이르매 거두리라'),
  ('ko', 165, '디모데후서 4:2', '너는 말씀을 전파하라 때를 얻든지 못 얻든지 항상 힘쓰라 범사에 오래 참음과 가르침으로 경책하며 경계하며 권하라'),
  ('ko', 166, '잠언 17:17', '친구는 사랑이 끊이지 아니하고 형제는 위급한 때까지 위하여 났느니라'),
  ('ko', 167, '에베소서 5:16', '세월을 아끼라 때가 악하니라'),
  ('ko', 168, '디모데후서 4:7', '내가 선한 싸움을 싸우고 나의 달려갈 길을 마치고 믿음을 지켰으니'),
  ('ko', 169, '마태복음 18:20', '두 세 사람이 내 이름으로 모인 곳에는 나도 그들 중에 있느니라'),
  ('ko', 170, '골로새서 3:23', '무슨 일을 하든지 마음을 다하여 주께 하듯하고 사람에게 하듯하지 말라'),
  ('ko', 171, '히브리서 11:13', '이 사람들은 다 믿음을 따라 죽었으며 약속을 받지 못하였으되 그것들을 멀리서 보고 환영하며 또 땅에서는 외국인과 나그네로라 증거하였으니'),
  ('ko', 172, '데살로니가전서 5:18', '범사에 감사하라 이는 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라'),
  ('ko', 173, '히브리서 12:1', '이러므로 우리에게 구름 같이 둘러싼 허다한 증인들이 있으니 모든 무거운 것과 얽매이기 쉬운 죄를 벗어 버리고 인내로써 우리 앞에 당한 경주를 경주하며'),
  ('ko', 174, '디모데후서 3:16', '모든 성경은 하나님의 감동으로 된 것으로 교훈과 책망과 바르게 함과 의로 교육하기에 유익하니'),
  ('ko', 175, '베드로전서 1:3', '찬송하리로다 우리 주 예수 그리스도의 아버지 하나님이 그 많으신 긍휼대로 예수 그리스도의 죽은 자 가운데서 부활하심으로 말미암아 우리를 거듭나게 하사 산 소망이 있게 하시며'),
  ('ko', 176, '야고보서 1:22', '너희는 도를 행하는 자가 되고 듣기만 하여 자신을 속이는 자가 되지말라'),
  ('ko', 177, '베드로전서 2:9', '오직 너희는 택하신 족속이요 왕 같은 제사장들이요 거룩한 나라요 그의 소유된 백성이니 이는 너희를 어두운데서 불러 내어 그의 기이한 빛에 들어가게 하신 자의 아름다운 덕을 선전하게 하려 하심이라'),
  ('ko', 178, '야고보서 4:8', '하나님을 가까이 하라 그리하면 너희를 가까이 하시리라 죄인들아 손을 깨끗이 하라 두 마음을 품은 자들아 마음을 성결케 하라'),
  ('ko', 179, '베드로전서 2:11', '사랑하는 자들아 나그네와 행인 같은 너희를 권하노니 영혼을 거스려 싸우는 육체의 정욕을 제어하라'),
  ('ko', 180, '베드로전서 3:15', '너희 마음에 그리스도를 주로 삼아 거룩하게 하고 너희 속에 있는 소망에 관한 이유를 묻는 자에게는 대답할 것을 항상 예비하되 온유와 두려움으로 하고'),
  ('ko', 181, '요한계시록 7:9', '이 일 후에 내가 보니 각 나라와 족속과 백성과 방언에서 아무라도 능히 셀 수 없는 큰 무리가 흰 옷을 입고 손에 종려 가지를 들고 보좌 앞과 어린 양 앞에 서서'),
  ('ko', 182, '요한계시록 21:5', '보좌에 앉으신 이가 가라사대 보라 내가 만물을 새롭게 하노라 하시고 또 가라사대 이 말은 신실하고 참되니 기록하라 하시고'),
  ('ko', 183, '요한계시록 22:20', '이것들을 증거하신 이가 가라사대 내가 진실로 속히 오리라 하시거늘 아멘 주 예수여 오시옵소서'),
  ('en', 1, 'Psalms 2:8', 'Ask of me, and I will give the nations for your inheritance, the uttermost parts of the earth for your possession.'),
  ('en', 2, 'Exodus 34:6', 'Yahweh passed by before him, and proclaimed, “Yahweh! Yahweh, a merciful and gracious God, slow to anger, and abundant in loving kindness and truth,'),
  ('en', 3, 'Joshua 1:9', 'Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.”'),
  ('en', 4, 'Proverbs 3:5', 'Trust in Yahweh with all your heart, and don’t lean on your own understanding.'),
  ('en', 5, 'John 13:34', 'A new commandment I give to you, that you love one another. Just as I have loved you, you also love one another.'),
  ('en', 6, 'Micah 6:8', 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?'),
  ('en', 7, 'Genesis 12:2', 'I will make of you a great nation. I will bless you and make your name great. You will be a blessing.'),
  ('en', 8, 'Psalms 145:8', 'Yahweh is gracious, merciful, slow to anger, and of great loving kindness.'),
  ('en', 9, 'Deuteronomy 31:8', 'Yahweh himself is who goes before you. He will be with you. He will not fail you nor forsake you. Don’t be afraid. Don’t be discouraged.”'),
  ('en', 10, 'Proverbs 3:6', 'In all your ways acknowledge him, and he will make your paths straight.'),
  ('en', 11, 'John 13:35', 'By this everyone will know that you are my disciples, if you have love for one another.”'),
  ('en', 12, 'Joshua 24:15', 'If it seems evil to you to serve Yahweh, choose today whom you will serve; whether the gods which your fathers served that were beyond the River, or the gods of the Amorites, in whose land you dwell; but as for me and my house, we will serve Yahweh.”'),
  ('en', 13, 'Genesis 28:15', 'Behold, I am with you, and will keep you, wherever you go, and will bring you again into this land. For I will not leave you until I have done that which I have spoken of to you.”'),
  ('en', 14, 'Psalms 145:18', 'Yahweh is near to all those who call on him, to all who call on him in truth.'),
  ('en', 15, 'Psalms 23:1', 'Yahweh is my shepherd; I shall lack nothing.'),
  ('en', 16, 'Proverbs 16:3', 'Commit your deeds to Yahweh, and your plans shall succeed.'),
  ('en', 17, 'John 15:5', 'I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.'),
  ('en', 18, 'Psalms 1:1', 'Blessed is the man who doesn’t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers;'),
  ('en', 19, 'Psalms 67:2', 'That your way may be known on earth, and your salvation among all nations,'),
  ('en', 20, 'Psalms 103:8', 'Yahweh is merciful and gracious, slow to anger, and abundant in loving kindness.'),
  ('en', 21, 'Psalms 23:4', 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.'),
  ('en', 22, 'Proverbs 16:9', 'A man’s heart plans his course, but Yahweh directs his steps.'),
  ('en', 23, 'John 15:12', '“This is my commandment, that you love one another, even as I have loved you.'),
  ('en', 24, 'Psalms 119:105', 'Your word is a lamp to my feet, and a light for my path.'),
  ('en', 25, 'Psalms 96:3', 'Declare his glory among the nations, his marvelous works among all the peoples.'),
  ('en', 26, 'Psalms 103:13', 'Like a father has compassion on his children, so Yahweh has compassion on those who fear him.'),
  ('en', 27, 'Psalms 27:1', 'Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid?'),
  ('en', 28, 'Psalms 37:4', 'Also delight yourself in Yahweh, and he will give you the desires of your heart.'),
  ('en', 29, 'John 15:13', 'Greater love has no one than this, that someone lay down his life for his friends.'),
  ('en', 30, 'Psalms 119:11', 'I have hidden your word in my heart, that I might not sin against you.'),
  ('en', 31, 'Isaiah 6:8', 'I heard the Lord’s voice, saying, “Whom shall I send, and who will go for us?” Then I said, “Here I am. Send me!”'),
  ('en', 32, 'Psalms 100:5', 'For Yahweh is good. His loving kindness endures forever, his faithfulness to all generations. Psalms < 100 >'),
  ('en', 33, 'Psalms 34:18', 'Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit.'),
  ('en', 34, 'Psalms 37:5', 'Commit your way to Yahweh. Trust also in him, and he will do this:'),
  ('en', 35, '1 Corinthians 13:4', 'Love is patient and is kind. Love doesn’t envy. Love doesn’t brag, is not proud,'),
  ('en', 36, 'Psalms 51:10', 'Create in me a clean heart, O God. Renew a right spirit within me.'),
  ('en', 37, 'Isaiah 9:6', 'For a child is born to us. A son is given to us; and the government will be on his shoulders. His name will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.'),
  ('en', 38, 'Psalms 136:1', 'Give thanks to Yahweh, for he is good, for his loving kindness endures forever.'),
  ('en', 39, 'Psalms 46:1', 'God is our refuge and strength, a very present help in trouble.'),
  ('en', 40, 'Psalms 18:2', 'Yahweh is my rock, my fortress, and my deliverer; my God, my rock, in whom I take refuge; my shield, and the horn of my salvation, my high tower.'),
  ('en', 41, '1 Corinthians 13:13', 'But now faith, hope, and love remain—these three. The greatest of these is love. 1 Corinthians < 13 >'),
  ('en', 42, 'Psalms 19:14', 'Let the words of my mouth and the meditation of my heart be acceptable in your sight, Yahweh, my rock, and my redeemer. Psalms < 19 >'),
  ('en', 43, 'Isaiah 43:19', 'Behold, I will do a new thing. It springs out now. Don’t you know it? I will even make a way in the wilderness, and rivers in the desert.'),
  ('en', 44, 'Psalms 90:2', 'Before the mountains were born, before you had formed the earth and the world, even from everlasting to everlasting, you are God.'),
  ('en', 45, 'Psalms 46:10', '“Be still, and know that I am God. I will be exalted among the nations. I will be exalted on the earth.”'),
  ('en', 46, 'Hebrews 11:1', 'Now faith is assurance of things hoped for, proof of things not seen.'),
  ('en', 47, '1 Corinthians 16:14', 'Let all that you do be done in love.'),
  ('en', 48, 'Psalms 90:12', 'So teach us to count our days, that we may gain a heart of wisdom.'),
  ('en', 49, 'Isaiah 49:6', 'Indeed, he says, “It is too light a thing that you should be my servant to raise up the tribes of Jacob, and to restore the preserved of Israel. I will also give you as a light to the nations, that you may be my salvation to the end of the earth.”'),
  ('en', 50, 'Psalms 139:1', 'Yahweh, you have searched me, and you know me.'),
  ('en', 51, 'Psalms 55:22', 'Cast your burden on Yahweh and he will sustain you. He will never allow the righteous to be moved.'),
  ('en', 52, 'Hebrews 11:6', 'Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him.'),
  ('en', 53, 'Romans 12:10', 'In love of the brothers be tenderly affectionate to one another; in honor prefer one another,'),
  ('en', 54, 'Psalms 118:24', 'This is the day that Yahweh has made. We will rejoice and be glad in it!'),
  ('en', 55, 'Isaiah 52:7', 'How beautiful on the mountains are the feet of him who brings good news, who publishes peace, who brings good news, who proclaims salvation, who says to Zion, “Your God reigns!”'),
  ('en', 56, 'Psalms 139:14', 'I will give thanks to you, for I am fearfully and wonderfully made. Your works are wonderful. My soul knows that very well.'),
  ('en', 57, 'Psalms 56:3', 'When I am afraid, I will put my trust in you.'),
  ('en', 58, 'Hebrews 12:2', 'looking to Jesus, the author and perfecter of faith, who for the joy that was set before him endured the cross, despising its shame, and has sat down at the right hand of the throne of God.'),
  ('en', 59, 'Romans 12:15', 'Rejoice with those who rejoice. Weep with those who weep.'),
  ('en', 60, 'Proverbs 1:7', 'The fear of Yahweh is the beginning of knowledge, but the foolish despise wisdom and instruction.'),
  ('en', 61, 'Isaiah 60:1', '“Arise, shine; for your light has come, and Yahweh’s glory has risen on you!'),
  ('en', 62, 'Lamentations 3:22', 'It is because of Yahweh’s loving kindnesses that we are not consumed, because his mercies don’t fail.'),
  ('en', 63, 'Psalms 62:1', 'My soul rests in God alone. My salvation is from him.'),
  ('en', 64, 'Romans 8:28', 'We know that all things work together for good for those who love God, for those who are called according to his purpose.'),
  ('en', 65, 'Romans 13:8', 'Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law.'),
  ('en', 66, 'Proverbs 4:23', 'Keep your heart with all diligence, for out of it is the wellspring of life.'),
  ('en', 67, 'Habakkuk 2:14', 'For the earth will be filled with the knowledge of Yahweh’s glory, as the waters cover the sea.'),
  ('en', 68, 'Isaiah 40:28', 'Haven’t you known? Haven’t you heard? The everlasting God, Yahweh, the Creator of the ends of the earth, doesn’t faint. He isn’t weary. His understanding is unsearchable.'),
  ('en', 69, 'Psalms 91:1', 'He who dwells in the secret place of the Most High will rest in the shadow of the Almighty.'),
  ('en', 70, 'Romans 8:31', 'What then shall we say about these things? If God is for us, who can be against us?'),
  ('en', 71, 'Romans 15:7', 'Therefore accept one another, even as Christ also accepted you, to the glory of God.'),
  ('en', 72, 'Proverbs 9:10', 'The fear of Yahweh is the beginning of wisdom. The knowledge of the Holy One is understanding.'),
  ('en', 73, 'Zechariah 4:6', 'Then he answered and spoke to me, saying, “This is Yahweh’s word to Zerubbabel, saying, ‘Not by might, nor by power, but by my Spirit,’ says Yahweh of Armies.'),
  ('en', 74, 'Isaiah 55:8', '“For my thoughts are not your thoughts, and your ways are not my ways,” says Yahweh.'),
  ('en', 75, 'Psalms 121:2', 'My help comes from Yahweh, who made heaven and earth.'),
  ('en', 76, 'Romans 8:37', 'No, in all these things we are more than conquerors through him who loved us.'),
  ('en', 77, 'Galatians 5:13', 'For you, brothers, were called for freedom. Only don’t use your freedom as an opportunity for the flesh, but through love be servants to one another.'),
  ('en', 78, 'Proverbs 15:1', 'A gentle answer turns away wrath, but a harsh word stirs up anger.'),
  ('en', 79, 'Matthew 24:14', 'This Good News of the Kingdom will be preached in the whole world for a testimony to all the nations, and then the end will come.'),
  ('en', 80, 'Isaiah 6:3', 'One called to another, and said, “Holy, holy, holy, is Yahweh of Armies! The whole earth is full of his glory!”'),
  ('en', 81, 'Psalms 121:8', 'Yahweh will keep your going out and your coming in, from this time forward, and forever more. Psalms < 121 >'),
  ('en', 82, 'Romans 10:17', 'So faith comes by hearing, and hearing by the word of God.'),
  ('en', 83, 'Galatians 6:2', 'Bear one another’s burdens, and so fulfill the law of Christ.'),
  ('en', 84, 'Proverbs 22:6', 'Train up a child in the way he should go, and when he is old he will not depart from it.'),
  ('en', 85, 'Matthew 28:19', 'Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,'),
  ('en', 86, 'Malachi 3:6', '“For I, Yahweh, don’t change; therefore you, sons of Jacob, are not consumed.'),
  ('en', 87, 'Psalms 147:3', 'He heals the broken in heart, and binds up their wounds.'),
  ('en', 88, 'Romans 1:17', 'For in it is revealed God’s righteousness from faith to faith. As it is written, “But the righteous shall live by faith.”'),
  ('en', 89, 'Ephesians 4:2', 'with all lowliness and humility, with patience, bearing with one another in love,'),
  ('en', 90, 'Ecclesiastes 3:1', 'For everything there is a season, and a time for every purpose under heaven:'),
  ('en', 91, 'Matthew 28:20', 'teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age.” Amen. Matthew < 28 >'),
  ('en', 92, 'John 1:14', 'The Word became flesh and lived among us. We saw his glory, such glory as of the only born Son of the Father, full of grace and truth.'),
  ('en', 93, 'Isaiah 40:31', 'but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint. Isaiah < 40 >'),
  ('en', 94, 'Galatians 2:20', 'I have been crucified with Christ, and it is no longer I who live, but Christ lives in me. That life which I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself up for me.'),
  ('en', 95, 'Ephesians 4:32', 'And be kind to one another, tender hearted, forgiving each other, just as God also in Christ forgave you. Ephesians < 4 >'),
  ('en', 96, 'Ecclesiastes 12:13', 'This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man.'),
  ('en', 97, 'Mark 16:15', 'He said to them, “Go into all the world and preach the Good News to the whole creation.'),
  ('en', 98, 'John 3:16', 'For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life.'),
  ('en', 99, 'Isaiah 41:10', 'Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.'),
  ('en', 100, 'Ephesians 2:8', 'for by grace you have been saved through faith, and that not of yourselves; it is the gift of God,'),
  ('en', 101, 'Colossians 3:13', 'bearing with one another, and forgiving each other, if any man has a complaint against any; even as Christ forgave you, so you also do.'),
  ('en', 102, 'Matthew 5:14', '“You are the light of the world. A city located on a hill can’t be hidden.'),
  ('en', 103, 'Acts 1:8', 'But you will receive power when the Holy Spirit has come upon you. You will be witnesses to me in Jerusalem, in all Judea and Samaria, and to the uttermost parts of the earth.”'),
  ('en', 104, 'John 4:24', 'God is spirit, and those who worship him must worship in spirit and truth.”'),
  ('en', 105, 'Isaiah 43:2', 'When you pass through the waters, I will be with you, and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you.'),
  ('en', 106, 'Mark 9:23', 'Jesus said to him, “If you can believe, all things are possible to him who believes.”'),
  ('en', 107, 'Colossians 3:14', 'Above all these things, walk in love, which is the bond of perfection.'),
  ('en', 108, 'Matthew 5:16', 'Even so, let your light shine before men, that they may see your good works and glorify your Father who is in heaven.'),
  ('en', 109, 'Acts 20:24', 'But these things don’t count; nor do I hold my life dear to myself, so that I may finish my race with joy, and the ministry which I received from the Lord Jesus, to fully testify to the Good News of the grace of God.'),
  ('en', 110, 'John 10:11', '“I am the good shepherd. The good shepherd lays down his life for the sheep.'),
  ('en', 111, 'Jeremiah 29:11', 'For I know the thoughts that I think toward you,” says Yahweh, “thoughts of peace, and not of evil, to give you hope and a future.'),
  ('en', 112, 'Mark 11:24', 'Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them.'),
  ('en', 113, 'Philippians 2:3', 'doing nothing through rivalry or through conceit, but in humility, each counting others better than himself;'),
  ('en', 114, 'Matthew 7:12', 'Therefore, whatever you desire for men to do to you, you shall also do to them; for this is the law and the prophets.'),
  ('en', 115, 'Romans 1:16', 'For I am not ashamed of the Good News of Christ, because it is the power of God for salvation for everyone who believes, for the Jew first, and also for the Greek.'),
  ('en', 116, 'John 11:25', 'Jesus said to her, “I am the resurrection and the life. He who believes in me will still live, even if he dies.'),
  ('en', 117, 'Matthew 11:28', '“Come to me, all you who labor and are heavily burdened, and I will give you rest.'),
  ('en', 118, 'Matthew 6:33', 'But seek first God’s Kingdom and his righteousness; and all these things will be given to you as well.'),
  ('en', 119, 'Philippians 2:4', 'each of you not just looking to his own things, but each of you also to the things of others.'),
  ('en', 120, 'Matthew 22:37', 'Jesus said to him, “ ‘You shall love the Lord your God with all your heart, with all your soul, and with all your mind.’'),
  ('en', 121, 'Romans 10:15', 'And how will they preach unless they are sent? As it is written: “How beautiful are the feet of those who preach the Good News of peace, who bring glad tidings of good things!”'),
  ('en', 122, 'John 14:6', 'Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.'),
  ('en', 123, 'John 14:27', 'Peace I leave with you. My peace I give to you; not as the world gives, I give to you. Don’t let your heart be troubled, neither let it be fearful.'),
  ('en', 124, 'Matthew 6:34', 'Therefore don’t be anxious for tomorrow, for tomorrow will be anxious for itself. Each day’s own evil is sufficient. Matthew < 6 >'),
  ('en', 125, 'Hebrews 10:24', 'Let’s consider how to provoke one another to love and good works,'),
  ('en', 126, 'Luke 9:23', 'He said to all, “If anyone desires to come after me, let him deny himself, take up his cross, and follow me.'),
  ('en', 127, 'Romans 15:13', 'Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope in the power of the Holy Spirit.'),
  ('en', 128, 'Romans 5:8', 'But God commends his own love toward us, in that while we were yet sinners, Christ died for us.'),
  ('en', 129, 'John 16:33', 'I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.” John < 16 >'),
  ('en', 130, 'Matthew 7:7', '“Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.'),
  ('en', 131, 'Hebrews 10:25', 'not forsaking our own assembling together, as the custom of some is, but exhorting one another, and so much the more as you see the Day approaching.'),
  ('en', 132, 'Romans 12:1', 'Therefore I urge you, brothers, by the mercies of God, to present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service.'),
  ('en', 133, '2 Corinthians 4:16', 'Therefore we don’t faint, but though our outward person is decaying, yet our inward person is renewed day by day.'),
  ('en', 134, 'Romans 11:36', 'For of him and through him and to him are all things. To him be the glory for ever! Amen. Romans < 11 >'),
  ('en', 135, '2 Corinthians 12:9', 'He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.'),
  ('en', 136, 'Philippians 4:13', 'I can do all things through Christ who strengthens me.'),
  ('en', 137, '1 Peter 4:8', 'And above all things be earnest in your love among yourselves, for love covers a multitude of sins.'),
  ('en', 138, 'Romans 12:2', 'Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.'),
  ('en', 139, '2 Corinthians 4:18', 'while we don’t look at the things which are seen, but at the things which are not seen. For the things which are seen are temporal, but the things which are not seen are eternal. 2 Corinthians < 4 >'),
  ('en', 140, '1 John 4:8', 'He who doesn’t love doesn’t know God, for God is love.'),
  ('en', 141, '1 Peter 5:7', 'casting all your worries on him, because he cares for you.'),
  ('en', 142, 'Philippians 1:6', 'being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ.'),
  ('en', 143, '1 John 3:18', 'My little children, let’s not love in word only, or with the tongue only, but in deed and truth.'),
  ('en', 144, 'Romans 12:12', 'rejoicing in hope, enduring in troubles, continuing steadfastly in prayer,'),
  ('en', 145, '2 Corinthians 5:20', 'We are therefore ambassadors on behalf of Christ, as though God were entreating by us: we beg you on behalf of Christ, be reconciled to God.'),
  ('en', 146, 'James 1:17', 'Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom can be no variation nor turning shadow.'),
  ('en', 147, 'Philippians 4:6', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.'),
  ('en', 148, '2 Corinthians 5:7', 'for we walk by faith, not by sight.'),
  ('en', 149, '1 John 4:7', 'Beloved, let’s love one another, for love is of God; and everyone who loves has been born of God and knows God.'),
  ('en', 150, 'Romans 12:21', 'Don’t be overcome by evil, but overcome evil with good. Romans < 12 >'),
  ('en', 151, 'Ephesians 3:20', 'Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us,'),
  ('en', 152, 'Hebrews 13:8', 'Jesus Christ is the same yesterday, today, and forever.'),
  ('en', 153, 'Revelation 21:4', 'He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more. The first things have passed away.”'),
  ('en', 154, 'John 20:29', 'Jesus said to him, “Because you have seen me, you have believed. Blessed are those who have not seen and have believed.”'),
  ('en', 155, '1 John 4:19', 'We love him, because he first loved us.'),
  ('en', 156, '1 Corinthians 10:31', 'Whether therefore you eat or drink, or whatever you do, do all to the glory of God.'),
  ('en', 157, 'Philippians 3:14', 'I press on toward the goal for the prize of the high calling of God in Christ Jesus.'),
  ('en', 158, 'Revelation 1:8', '“I am the Alpha and the Omega,” says the Lord God, “who is and who was and who is to come, the Almighty.”'),
  ('en', 159, 'James 1:5', 'But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.'),
  ('en', 160, 'Ecclesiastes 4:12', 'If a man prevails against one who is alone, two shall withstand him; and a threefold cord is not quickly broken.'),
  ('en', 161, '2 Corinthians 5:17', 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.'),
  ('en', 162, 'Philippians 3:20', 'For our citizenship is in heaven, from where we also wait for a Savior, the Lord Jesus Christ,'),
  ('en', 163, 'Psalms 133:1', 'See how good and how pleasant it is for brothers to live together in unity!'),
  ('en', 164, 'Galatians 6:9', 'Let’s not be weary in doing good, for we will reap in due season if we don’t give up.'),
  ('en', 165, '2 Timothy 4:2', 'preach the word; be urgent in season and out of season; reprove, rebuke, and exhort with all patience and teaching.'),
  ('en', 166, 'Proverbs 17:17', 'A friend loves at all times; and a brother is born for adversity.'),
  ('en', 167, 'Ephesians 5:16', 'redeeming the time, because the days are evil.'),
  ('en', 168, '2 Timothy 4:7', 'I have fought the good fight. I have finished the course. I have kept the faith.'),
  ('en', 169, 'Matthew 18:20', 'For where two or three are gathered together in my name, there I am in the middle of them.”'),
  ('en', 170, 'Colossians 3:23', 'And whatever you do, work heartily, as for the Lord and not for men,'),
  ('en', 171, 'Hebrews 11:13', 'These all died in faith, not having received the promises, but having seen them and embraced them from afar, and having confessed that they were strangers and pilgrims on the earth.'),
  ('en', 172, '1 Thessalonians 5:18', 'In everything give thanks, for this is the will of God in Christ Jesus toward you.'),
  ('en', 173, 'Hebrews 12:1', 'Therefore let’s also, seeing we are surrounded by so great a cloud of witnesses, lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us,'),
  ('en', 174, '2 Timothy 3:16', 'Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness,'),
  ('en', 175, '1 Peter 1:3', 'Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead,'),
  ('en', 176, 'James 1:22', 'But be doers of the word, and not only hearers, deluding your own selves.'),
  ('en', 177, '1 Peter 2:9', 'But you are a chosen race, a royal priesthood, a holy nation, a people for God’s own possession, that you may proclaim the excellence of him who called you out of darkness into his marvelous light.'),
  ('en', 178, 'James 4:8', 'Draw near to God, and he will draw near to you. Cleanse your hands, you sinners. Purify your hearts, you double-minded.'),
  ('en', 179, '1 Peter 2:11', 'Beloved, I beg you as foreigners and pilgrims to abstain from fleshly lusts which war against the soul,'),
  ('en', 180, '1 Peter 3:15', 'But sanctify the Lord God in your hearts. Always be ready to give an answer to everyone who asks you a reason concerning the hope that is in you, with humility and fear,'),
  ('en', 181, 'Revelation 7:9', 'After these things I looked, and behold, a great multitude which no man could count, out of every nation and of all tribes, peoples, and languages, standing before the throne and before the Lamb, dressed in white robes, with palm branches in their hands.'),
  ('en', 182, 'Revelation 21:5', 'He who sits on the throne said, “Behold, I am making all things new.” He said, “Write, for these words of God are faithful and true.”'),
  ('en', 183, 'Revelation 22:20', 'He who testifies these things says, “Yes, I am coming soon.” Amen! Yes, come, Lord Jesus!'),
  ('km', 1, 'ទំនុកដំកើង 2:8', 'ចូរ​សូម​ពី​អញ នោះ​អញ​នឹង​ឲ្យ​សាសន៍​ទាំងឡាយ​ដល់​ឯង ទុក​ជា​មរដក ហើយ​អស់​ទាំង​ចុង​ផែនដី​ទុក​ជា​កេរអាករ​របស់​ឯង'),
  ('km', 2, 'និក្ខមនំ 34:6', 'ទ្រង់​យាង​កាត់​នៅ​មុខ​លោក​ទាំង​ប្រកាស​ថា យេហូវ៉ា គឺ​យេហូវ៉ា​ដ៏​ជា​ព្រះ​ទ្រង់​មាន​ព្រះហឫទ័យ​មេត្តាករុណា ហើយ​ទន់​សន្តោស ទ្រង់​យឺត​នឹង​ខ្ញាល់ ហើយ​មាន​សេចក្តី​សប្បុរស និង​សេចក្តី​ទៀង​ត្រង់ ជា​បរិបូរ'),
  ('km', 3, 'យ៉ូស្វេ 1:9', 'តើ​អញ​មិន​បាន​បង្គាប់​ឯង​ទេ​ឬ​អី ដូច្នេះ​ចូរ​ឲ្យ​មាន​កំឡាំង និង​ចិត្ត​ក្លាហាន​ចុះ កុំ​ឲ្យ​ខ្លាច​ឡើយ ក៏​កុំ​ឲ្យ​ស្រយុត​ចិត្ត​ផង ដ្បិត​ព្រះយេហូវ៉ា​ជា​ព្រះ​នៃ​ឯង ទ្រង់​គង់​ជា​មួយ​នៅ​កន្លែង​ណា ដែល​ឯង​ទៅ​ផង។'),
  ('km', 4, 'សុភាសិត 3:5', 'ចូរ​ទី​ពឹង​ដល់​ព្រះយេហូវ៉ា​ឲ្យ​អស់​អំពី​ចិត្ត កុំ​ឲ្យ​ពឹង​ផ្អែក​លើ​យោបល់​របស់​ខ្លួន​ឡើយ'),
  ('km', 5, 'យ៉ូហាន 13:34', 'ខ្ញុំ​ឲ្យ​សេចក្តី​បញ្ញត្ត​១​ថ្មី​ដល់​អ្នក​រាល់​គ្នា គឺ​ឲ្យ​អ្នក​រាល់​គ្នា​ស្រឡាញ់​គ្នា​ទៅ​វិញ​ទៅ​មក ត្រូវ​ឲ្យ​ស្រឡាញ់​គ្នា ដូច​ជា​ខ្ញុំ​បាន​ស្រឡាញ់​អ្នក​រាល់​គ្នា​ដែរ'),
  ('km', 6, 'មីកា 6:8', 'ឱ​មនុស្ស​អើយ ព្រះ​បាន​បង្ហាញ​ឲ្យ​ឯង​ស្គាល់​សេចក្តី​ដែល​ល្អ តើ​ព្រះយេហូវ៉ា​សព្វ​ព្រះហឫទ័យ​ឲ្យ​ឯង​ប្រព្រឹត្ត​ដូច​ម្តេច បើ​មិន​មែន​ឲ្យ​ប្រព្រឹត្ត​ដោយ​សុចរិត ឲ្យ​ស្រឡាញ់​សេចក្តី​សប្បុរស ហើយ​ឲ្យ​ដើរ​ជា​មួយ​នឹង​ព្រះ​នៃ​ខ្លួន ដោយ​សុភាព​រាបទាបប៉ុណ្ណោះ។'),
  ('km', 7, 'លោកុប្បត្តិ 12:2', 'អញ​នឹង​បង្កើត​នគរ​១​យ៉ាង​ធំ​ពី​ឯង អញ​នឹង​ឲ្យ​ពរ​ដល់​ឯង ទាំង​លើក​ឈ្មោះ​ឯង​ធំ​ផង ឯង​នឹង​បាន​ធ្វើ​ជា​ទី​បញ្ចេញ​ពរ​ដល់​មនុស្ស​ទាំងឡាយ'),
  ('km', 8, 'ទំនុកដំកើង 145:8', 'ព្រះយេហូវ៉ា​ទ្រង់​ប្រកប​ដោយ​មេត្តាករុណា និង​អាណិតអាសូរ ទ្រង់​យឺត​នឹង​ខ្ញាល់ ក៏​មាន​សេចក្តី​សប្បុរស​ដ៏​ធំ​ទូលាយ'),
  ('km', 9, 'ចោទិយកថា 31:8', 'គឺ​ព្រះយេហូវ៉ា​ដែល​នឹង​យាង​នាំ​មុខ​ឯង​ទៅ ព្រម​ទាំង​គង់​ជា​មួយ​នឹង​ឯង ទ្រង់​មិន​ដែល​ខាន​នឹង​ប្រោស​ឯង​ឡើយ ក៏​មិន​ដែល​លះ​ចោល​ឯង​ដែរ ដូច្នេះ​កុំ​ឲ្យ​ខ្លាច ឬ​ស្រយុត​ចិត្ត​ឲ្យ​សោះ។'),
  ('km', 10, 'សុភាសិត 3:6', 'ត្រូវ​ឲ្យ​ទទួល​ស្គាល់​ទ្រង់​នៅ​គ្រប់​ទាំង​ផ្លូវ​ឯង​ចុះ នោះ​ទ្រង់​នឹង​ដំរង់​អស់​ទាំង​ផ្លូវ​ច្រក​របស់​ឯង'),
  ('km', 11, 'យ៉ូហាន 13:35', 'គេ​នឹង​ដឹង​ថា អ្នក​រាល់​គ្នា​ជា​សិស្ស​របស់​ខ្ញុំ ដោយសារ​សេចក្តី​នេះ​ឯង គឺ​ដោយ​អ្នក​រាល់​គ្នា​មាន​សេចក្តី​ស្រឡាញ់​ដល់​គ្នា​ទៅ​វិញ​ទៅ​មក។'),
  ('km', 12, 'យ៉ូស្វេ 24:15', 'តែ​បើសិន​ជា​ឯង​រាល់​គ្នា​មិន​គាប់​ចិត្ត​នឹង​គោរព​ប្រតិបត្តិ​ដល់​ព្រះយេហូវ៉ា​ទេ នោះ​ចូរ​រើស​យក​ព្រះ​ណា ដែល​ឯង​ចង់​គោរព​ប្រតិបត្តិ​តាម​នៅ​ថ្ងៃ​នេះ​ចុះ ទោះ​បើ​ជា​ព្រះ​ទាំង​ប៉ុន្មាន ដែល​ពួក​ឰយុកោ​ឯង​បាន​គោរព​ប្រតិបត្តិ​នៅ​ខាង​នាយ​ទន្លេ ឬ​អស់​ទាំង​ព្រះ​របស់​សាសន៍​អាម៉ូរី​នេះ ដែល​ឯង​រាល់​គ្នា​នៅ​ក្នុង​ស្រុក​គេ​ក្តី តែ​ឯ​អញ និង​ពួក​គ្រួ​អញ យើង​ទាំង​អស់​គ្នា​នឹង​គោរព​ប្រតិបត្តិ​ដល់​ព្រះយេហូវ៉ា​តែ​មួយ​ប៉ុណ្ណោះ។'),
  ('km', 13, 'លោកុប្បត្តិ 28:15', 'មើល អញ​នៅ​ជា​មួយ​នឹង​ឯង អញ​នឹង​ថែ​រក្សា​ឯង​នៅ​កន្លែង​ណា​ដែល​ឯង​ទៅ ហើយ​នឹង​ថែ​រក្សា​ឯង​នៅ​កន្លែង​ណា​ដែល​ឯង​ទៅ ហើយ​នឹង​នាំ​ឯង​មក​ក្នុង​ស្រុក​នេះ​វិញ ពី​ព្រោះ​អញ​មិន​ចោល​ឯង​ឡើយ ទាល់​តែ​អញ​បាន​ធ្វើ​សំរេច​សេចក្តី​ដែល​អញ​បាន​ប្រាប់​ឯង​ហើយ។'),
  ('km', 14, 'ទំនុកដំកើង 145:18', 'ព្រះយេហូវ៉ា​ទ្រង់​គង់​នៅ​ជិត​នឹង​អស់​អ្នក ដែល​អំពាវនាវ​ដល់​ទ្រង់ គឺ​អស់​អ្នក​ដែល​អំពាវនាវ​ដល់​ទ្រង់​ដោយ​ពិត​ត្រង់'),
  ('km', 15, 'ទំនុកដំកើង 23:1', 'ព្រះយេហូវ៉ា​ទ្រង់​ជា​អ្នក​គង្វាល​ខ្ញុំ ខ្ញុំ​នឹង​មិន​ខ្វះ​អ្វី​សោះ'),
  ('km', 16, 'សុភាសិត 16:3', 'ចូរ​ទុក​ដាក់​អស់​ទាំង​ការ​ឯង នៅ​នឹង​ព្រះយេហូវ៉ា​ចុះ នោះ​អស់​ទាំង​គំនិត​របស់​ឯង នឹង​បាន​សំរេច។'),
  ('km', 17, 'យ៉ូហាន 15:5', 'ខ្ញុំ​ជា​គល់ អ្នក​រាល់​គ្នា​ជា​ខ្នែង អ្នក​ណា​ដែល​នៅ​ជាប់​នឹង​ខ្ញុំ ហើយ​ខ្ញុំ​ជាប់​នឹង​អ្នក​នោះ នោះ​ទើប​នឹង​បង្កើត​ផល​ឡើង​ជា​ច្រើន ដ្បិត​បើ​ដាច់​ពី​ខ្ញុំ​ចេញ នោះ​អ្នក​រាល់​គ្នា​ពុំ​អាច​នឹង​ធ្វើ​អ្វី​បាន​ទេ'),
  ('km', 18, 'ទំនុកដំកើង 1:1', 'មាន​ពរ​ហើយ អ្នក​ណា​ដែល​មិន​ដើរ​តាម​ដំបូន្មាន របស់​មនុស្ស​អាក្រក់ ក៏​មិន​ឈរ​នៅ​ក្នុង​ផ្លូវ​របស់​មនុស្ស​មាន​បាប ឬ​អង្គុយ​នៅ​ជា​មួយ​នឹង​ពួក​មនុស្ស​ដែល​មើលងាយ'),
  ('km', 19, 'ទំនុកដំកើង 67:2', '៙ ដើម្បី​ឲ្យ​មនុស្ស​លោក​បាន​ស្គាល់​ផ្លូវ​របស់​ទ្រង់ ហើយ​ឲ្យ​អស់​ទាំង​សាសន៍​ដទៃ​បាន​ស្គាល់​សេចក្តី សង្គ្រោះ​របស់​ទ្រង់​ដែរ'),
  ('km', 20, 'ទំនុកដំកើង 103:8', 'ព្រះយេហូវ៉ា​ទ្រង់​មាន​សេចក្តី​មេត្តាករុណា ហើយ​នឹង​អាណិតអាសូរ ទ្រង់​យឺត​នឹង​ខ្ញាល់ ហើយ​មាន​សេចក្តី​សប្បុរស​ដ៏​បរិបូរ'),
  ('km', 21, 'ទំនុកដំកើង 23:4', '៙ អើ ទោះ​បើ​ទូលបង្គំ​ដើរ​កាត់​ច្រក​ភ្នំ​នៃ​ម្លប់​សេចក្តី​ស្លាប់ក៏​ដោយ គង់​តែ​មិន​ខ្លាច​សេចក្តី​អាក្រក់​ណា​ឡើយ ដ្បិត​ទ្រង់​គង់​នៅ​ជា​មួយ​នឹង​ទូលបង្គំ ព្រនង់ ហើយ​នឹង​ដំបង​របស់​ទ្រង់​កំសាន្ត​ចិត្ត​ទូលបង្គំ'),
  ('km', 22, 'សុភាសិត 16:9', 'ចិត្ត​របស់​មនុស្ស​រមែង​គិត​សំរេច​ផ្លូវ​របស់​ខ្លួន តែ​គឺ​ព្រះយេហូវ៉ា​ដែល​ទ្រង់​ដំរង់​ជំហាន​គេ​វិញ។'),
  ('km', 23, 'យ៉ូហាន 15:12', 'នេះ​ជា​សេចក្តី​បញ្ញត្ត​របស់​ខ្ញុំ គឺ​ឲ្យ​អ្នក​រាល់​គ្នា​ស្រឡាញ់​ដល់​គ្នា​ទៅ​វិញ​ទៅ​មក ដូច​ជា​ខ្ញុំ​បាន​ស្រឡាញ់​អ្នក​រាល់​គ្នា​ដែរ'),
  ('km', 24, 'ទំនុកដំកើង 119:105', '៙ ព្រះបន្ទូល​នៃ​ទ្រង់​ជា​ចង្កៀង​ដល់​ជើង​ទូលបង្គំ ហើយ​ជា​ពន្លឺ​បំភ្លឺ​ផ្លូវ​ទូលបង្គំ​ផង'),
  ('km', 25, 'ទំនុកដំកើង 96:3', 'ចូរ​ថ្លែង​ប្រាប់​ពី​សិរីល្អ​ទ្រង់ នៅ​កណ្តាល​អស់​ទាំង​សាសន៍ ហើយ​ពី​ការ​អស្ចារ្យ​របស់​ទ្រង់ នៅ​កណ្តាល​បណ្តាជន​ទាំងឡាយ'),
  ('km', 26, 'ទំនុកដំកើង 103:13', 'ព្រះយេហូវ៉ា​ទ្រង់​មាន​ព្រះហឫទ័យ​អាណិត​ដល់​អស់​អ្នក ដែល​កោតខ្លាច​ទ្រង់ ដូច​ជា​ឪពុក​មាន​ចិត្ត​អាសូរ​ដល់​កូន​របស់​ខ្លួន​ដែរ'),
  ('km', 27, 'ទំនុកដំកើង 27:1', 'ព្រះយេហូវ៉ា​ទ្រង់​ជា​ពន្លឺ ហើយ​ជា​សេចក្តី សង្គ្រោះ​របស់​ខ្ញុំ តើ​ខ្ញុំ​នឹង​ត្រូវ​ខ្លាច​ចំពោះ​អ្នក​ណា ព្រះយេហូវ៉ា​ទ្រង់​ជា​ទី​ពឹង​ពំនាក់​នៃ​ជីវិត​ខ្ញុំ តើ​ត្រូវ​ឲ្យ​ខ្ញុំ​ភ័យ​ចំពោះ​អ្នក​ណា'),
  ('km', 28, 'ទំនុកដំកើង 37:4', 'ចូរ​យក​ព្រះយេហូវ៉ា​ជា​សេចក្តី​អំណរ​របស់​អ្នក នោះ​ទ្រង់​នឹង​ប្រទាន​ឲ្យ​អ្នក​បាន​ដូច​បំណង​ចិត្ត'),
  ('km', 29, 'យ៉ូហាន 15:13', 'គ្មាន​អ្នក​ណា​មាន​សេចក្តី​ស្រឡាញ់​ធំ​ជាង​នេះ គឺ​ដែល​អ្នក​ណា​នឹង​ប្តូរ​ជីវិត ជំនួស​ពួក​សំឡាញ់​របស់​ខ្លួន​នោះ​ទេ'),
  ('km', 30, 'ទំនុកដំកើង 119:11', 'ទូលបង្គំ​បាន​កំណត់​ចាំ​ព្រះបន្ទូល​ទ្រង់​ទុក​នៅ​ក្នុង​ចិត្ត ប្រយោជន៍​កុំ​ឲ្យ​ទូលបង្គំ​ធ្វើ​បាប​នឹង​ទ្រង់​ឡើយ'),
  ('km', 31, 'អេសាយ 6:8', 'រួច​ខ្ញុំ​ឮ​សូរសៀង​របស់​ព្រះអម្ចាស់ មាន​ព្រះបន្ទូល​មក​ថា តើ​អញ​នឹង​ចាត់​អ្នក​ណា​ឲ្យ​ទៅ តើ​អ្នក​ណា​នឹង​ទៅ​ឲ្យ​អញ នោះ​ខ្ញុំ​ទូល​ឆ្លើយ​ថា ទូលបង្គំ​នៅ​ឯ​ណេះ​ហើយ សូម​ចាត់​ទូលបង្គំ​ចុះ'),
  ('km', 32, 'ទំនុកដំកើង 100:5', 'ពី​ព្រោះ​ព្រះយេហូវ៉ា​ទ្រង់​ល្អ សេចក្តី​សប្បុរស​នៃ​ទ្រង់​ស្ថិតស្ថេរ​នៅ​ជានិច្ច ហើយ​សេចក្តី​ស្មោះត្រង់​របស់​ទ្រង់ ក៏​នៅ​អស់​ទាំង​ដំណ​មនុស្ស​ត​ទៅ។ ទំនុកដំកើង < ១០០ >'),
  ('km', 33, 'ទំនុកដំកើង 34:18', 'ព្រះយេហូវ៉ា​ទ្រង់​គង់​ជិត​បង្កើយ​នឹង​អស់​អ្នក ដែល​មាន​ចិត្ត​សង្រេង ហើយ​ទ្រង់​ជួយ​សង្គ្រោះ​ដល់​អស់​អ្នក ដែល​មាន​វិញ្ញាណ​ទន់​ទាប'),
  ('km', 34, 'ទំនុកដំកើង 37:5', 'ចូរ​ទុក​ដាក់​ផ្លូវ​អ្នក​នឹង​ព្រះយេហូវ៉ា​ចុះ ថែម​ទាំង​ទុក​ចិត្ត​ដល់​ទ្រង់​ផង នោះ​ទ្រង់​នឹង​ប្រោស​ឲ្យ​បាន​សំរេច'),
  ('km', 35, 'កូរិនថូសទី ១ 13:4', 'ឯ​សេចក្តី​ស្រឡាញ់​តែង​តែ​អត់ធ្មត់ ហើយ​ក៏​សប្បុរស សេចក្តី​ស្រឡាញ់​មិន​ចេះ​ឈ្នានីស មិន​ចេះ​អួត​ខ្លួន ក៏​មិន​ដែល​មាន​ចិត្ត​ធំ​ផង'),
  ('km', 36, 'ទំនុកដំកើង 51:10', 'ឱ​ព្រះអង្គ​អើយ សូម​បង្កើត​ចិត្ត​បរិសុទ្ធ​នៅ​ក្នុង​ទូលបង្គំ ហើយ​កែ​វិញ្ញាណ​ក្នុង​ទូលបង្គំ​ឲ្យ​ត្រឹម​ត្រូវ​ឡើង'),
  ('km', 37, 'អេសាយ 9:6', 'ដ្បិត​មាន​បុត្រ​១​កើត​ដល់​យើង ព្រះ​ទ្រង់​ប្រទាន​បុត្រា​១​មក​យើង​ហើយ ឯ​ការ​គ្រប់គ្រង​នឹង​នៅ​លើ​ស្មា​របស់​បុត្រ​នោះ ហើយ​គេ​នឹង​ហៅ​ព្រះនាម​ទ្រង់​ថា ព្រះ​ដ៏​ជួយ​គំនិត​យ៉ាង​អស្ចារ្យ ព្រះ​ដ៏​មាន​ព្រះចេស្តា ព្រះវបិតា​ដ៏​គង់​នៅ​អស់កល្ប និង​ជា​ម្ចាស់​នៃ​មេត្រីភាព'),
  ('km', 38, 'ទំនុកដំកើង 136:1', 'ឱ​សូម​អរ​ព្រះគុណ​ដល់​ព្រះយេហូវ៉ា ដ្បិត​ទ្រង់​ល្អ សេចក្តី​សប្បុរស​របស់​ទ្រង់​ស្ថិតស្ថេរ​នៅ​ជា​ដរាប'),
  ('km', 39, 'ទំនុកដំកើង 46:1', 'ព្រះ​ទ្រង់​ជា​ទី​ពឹង​ជ្រក ក៏​ជា​កំឡាំង​នៃ​យើង​ខ្ញុំ ជា​ជំនួយ​ដែល​នៅ​ជាប់​ជា​មួយ​ក្នុង​គ្រា​អាសន្ន'),
  ('km', 40, 'ទំនុកដំកើង 18:2', 'ព្រះយេហូវ៉ា​ទ្រង់​ជា​ថ្មដា ជា​បន្ទាយ ហើយ​ជា​អ្នក​ជួយ​សង្គ្រោះ​របស់​ទូលបង្គំ គឺ​ជា​ព្រះ​នៃ​ទូលបង្គំ ជា​ថ្មដា​ដែល​ទូលបង្គំ​យក​ជា​ទី​ពឹង ក៏​ជា​ខែល ជា​ស្នែង​នៃ​សេចក្តី​សង្គ្រោះ​របស់​ទូលបង្គំ ហើយ​ជា​ប៉ម​យ៉ាង​ខ្ពស់​ផង'),
  ('km', 41, 'កូរិនថូសទី ១ 13:13', 'ឥឡូវ​នេះ នៅ​មាន​សេចក្តី​ជំនឿ សេចក្តី​សង្ឃឹម និង​សេចក្តី​ស្រឡាញ់ ទាំង​៣​មុខ​នេះ តែ​សេចក្តី​ដែល​វិសេស​ជាង​គេ គឺ​ជា​សេចក្តី​ស្រឡាញ់។ កូរិនថូសទី ១ < ១៣ >'),
  ('km', 42, 'ទំនុកដំកើង 19:14', 'ឱ​ព្រះយេហូវ៉ា ជា​ថ្មដា ហើយ​ជា​អ្នក​ប្រោស​លោះ​នៃ ទូលបង្គំ​អើយ សូម​ឲ្យ​ពាក្យ​សំដី​ដែល​ចេញ​មក​ពី​មាត់​ទូលបង្គំ និង​ការ​រំពឹង​គិត​ក្នុង​ចិត្ត​របស់​ទូលបង្គំ បាន​គួរ​គាប់​នៅ​ព្រះនេត្រ​ទ្រង់។ ទំនុកដំកើង < ១៩ >'),
  ('km', 43, 'អេសាយ 43:19', 'មើល អញ​នឹង​ធ្វើ​ការ​១​ថ្មី​វិញ ការ​នោះ​នឹង​លេច​ឡើង​ឥឡូវ តើ​ឯង​រាល់​គ្នា​នឹង​មិន​ស្គាល់​ទេ​ឬ អញ​នឹង​ធ្វើ​ផ្លូវ​១​នៅ​ទី​រហោស្ថាន ហើយ​ទន្លេ​នៅ​សមុទ្រ​ខ្សាច់'),
  ('km', 44, 'ទំនុកដំកើង 90:2', 'គឺ​មុន​ដែល​អស់​ទាំង​ភ្នំ​បាន​កើត​ឡើង ក្នុង​កាល​ដែល​ទ្រង់​មិន​ទាន់​បង្កើត​ផែនដី និង​មនុស្ស​លោក​នៅ​ឡើយ ចាប់​តាំង​ពី​អស់កល្ប រៀង​ទៅ​ដល់​អស់កល្ប​ជានិច្ច នោះ​គឺ​ទ្រង់​ហើយ​ជា​ព្រះ'),
  ('km', 45, 'ទំនុកដំកើង 46:10', 'ចូរ​បង្អង់​សិន ឲ្យ​បាន​ដឹង​ថា អញ​ជា​ព្រះ អញ​នឹង​បាន​ថ្កើង​ឡើង នៅ​កណ្តាល​ពួក​សាសន៍​ដទៃ អញ​នឹង​បាន​ថ្កើង​ឡើង​នៅ​ផែនដី'),
  ('km', 46, 'ហេព្រើរ 11:1', 'រីឯ​សេចក្តី​ជំនឿ នោះ​គឺ​ជា​ចិត្ត​ដែល​ដឹង​ជាក់​ថា​នឹង​បានដូច​សង្ឃឹម ជា​សំគាល់​ពី​ការ​ដែល​មើល​មិន​ឃើញ'),
  ('km', 47, 'កូរិនថូសទី ១ 16:14', 'ត្រូវ​ឲ្យ​អ្នក​រាល់​គ្នា​ធ្វើ​ការ​ទាំង​អស់ ដោយ​សេចក្តី​ស្រឡាញ់។'),
  ('km', 48, 'ទំនុកដំកើង 90:12', 'ដូច្នេះ សូម​បង្រៀន​ឲ្យ​យើង​ខ្ញុំ​ចេះ​កំណត់​រាប់​ថ្ងៃ​អាយុ នៃ​យើង​ខ្ញុំ ដើម្បី​ឲ្យ​យើង​ខ្ញុំ​មាន​ចិត្ត​ខ្មីឃ្មាត ឲ្យ​បាន​សតិបញ្ញា'),
  ('km', 49, 'អេសាយ 49:6', 'អើ ទ្រង់​មាន​ព្រះបន្ទូល​ថា ការ​ដែល​ឯង​ធ្វើ​ជា​អ្នក​បំរើ​របស់​អញ ដើម្បី​លើក​អស់​ទាំង​ពូជ​អំបូរ​នៃ​យ៉ាកុប​ឡើង ហើយ​នឹង​នាំ​ពួក​បំរុង​ទុក​ក្នុង​សាសន៍​អ៊ីស្រាអែល​ឲ្យ​មក​វិញ នោះ​ជា​ការ​តិចតួច​ពេក​ដល់​ឯង អញ​នឹង​បន្ថែម​ការ​នេះ​ឲ្យ​ឯង​បាន​ធ្វើ​ជា​ពន្លឺ​ដល់​សាសន៍​ដទៃ​ទាំង​ប៉ុន្មាន​ទៀត ដើម្បី​ឲ្យ​ឯង​បាន​ធ្វើ​ជា​អ្នក​ជួយ​សង្គ្រោះ​របស់​អញ រហូត​ដល់​ចុង​ផែនដី​បំផុត'),
  ('km', 50, 'ទំនុកដំកើង 139:1', 'ឱ​ព្រះយេហូវ៉ា​អើយ ទ្រង់​បាន​ពិនិត្យ​មើល ហើយ​បាន​ស្គាល់​ទូលបង្គំ​ផង'),
  ('km', 51, 'ទំនុកដំកើង 55:22', 'ចូរ​ផ្ទេរ​បន្ទុក​របស់​អ្នក​ទៅ​លើ​ព្រះយេហូវ៉ា នោះ​ទ្រង់​នឹង​ជួយ​ទប់ទល់​អ្នក ទ្រង់​មិន​ព្រម​ឲ្យ​មនុស្ស​សុចរិត​ត្រូវ​រង្គើ​ឡើយ'),
  ('km', 52, 'ហេព្រើរ 11:6', 'តែ​បើ​ឥត​មាន​សេចក្តី​ជំនឿ​ទេ នោះ​មិន​អាច​នឹង​គាប់​ដល់​ព្រះហឫទ័យ​ព្រះ​បាន​ឡើយ ដ្បិត​អ្នក​ណា​ដែល​ចូល​ទៅ​ឯ​ព្រះ នោះ​ត្រូវ​តែ​ជឿ​ថា មាន​ព្រះ​មែន ហើយ​ថា ទ្រង់​ប្រទាន​រង្វាន់ ដល់​អស់​អ្នក​ដែល​ស្វែង​រក​ទ្រង់។'),
  ('km', 53, 'រ៉ូម 12:10', 'ខាង​ឯ​សេចក្តី​ស្រឡាញ់​ជា​បង​ជា​ប្អូន នោះ​ចូរ​មាន​ចិត្ត​ថ្នម​គ្នា​ទៅ​វិញ​ទៅ​មក​ចុះ ខាង​ឯ​សេចក្តី​រាប់​អាន នោះ​ឲ្យ​ខំ​រាប់​អាន​គេ​ជា​មុន'),
  ('km', 54, 'ទំនុកដំកើង 118:24', 'ថ្ងៃ​នេះ​ជា​ថ្ងៃ​ដែល​ព្រះយេហូវ៉ា​បាន​កំណត់​ទុក នៅ​ថ្ងៃ​នេះ យើង​រាល់​គ្នា​នឹង​រីករាយ​សប្បាយ​ឡើង។'),
  ('km', 55, 'អេសាយ 52:7', 'អើ ល្អ​ណាស់​ហ្ន៎ គឺ​ជើង​នៃ​អ្នក​នោះ​ដែល​ដើរ​លើ​ភ្នំ ជា​អ្នក​ដែល​នាំ​ដំណឹង​ល្អ​មក ហើយ​ប្រកាស​ប្រាប់​ពី​សេចក្តី​មេត្រី ជា​អ្នក​ដែល​នាំ​ដំណឹង​ល្អ​ពី​ការ​ប្រសើរ​មក ហើយ​ថ្លែង​ប្រាប់​ពី​សេចក្តី​សង្គ្រោះ គឺ​ជា​អ្នក​ដែល​ពោល​ដល់​ក្រុង​ស៊ីយ៉ូន​ថា ព្រះ​នៃ​ឯង​ទ្រង់​សោយរាជ្យ'),
  ('km', 56, 'ទំនុកដំកើង 139:14', 'ទូលបង្គំ​នឹង​អរ​ព្រះគុណ​ដល់​ទ្រង់ ដ្បិត​ទ្រង់​បាន​បង្កើត​ទូលបង្គំ​មក​យ៉ាង​គួរ​កោត គួរ​អស្ចារ្យ ឯ​ស្នាដៃ​នៃ​ទ្រង់ ក៏​សុទ្ធ​តែ​អស្ចារ្យ​ទាំង​អស់ ព្រលឹង​ទូលបង្គំ​ក៏​ដឹង​ច្បាស់​ហើយ'),
  ('km', 57, 'ទំនុកដំកើង 56:3', 'តែ​វេលា​ណា​ដែល​ទូលបង្គំ​ភ័យ នោះ​ទូលបង្គំ​នឹង​ទុក​ចិត្ត​ដល់​ទ្រង់'),
  ('km', 58, 'ហេព្រើរ 12:2', 'ទាំង​រំពឹង​មើល​ដល់​ព្រះយេស៊ូវ​ដ៏​ជា​មេ​ផ្តើម ហើយ​ជា​មេ​សំរេច​សេចក្តី​ជំនឿ​របស់​យើង ដែល​ទ្រង់​បាន​រង​ទ្រាំ​នៅ​ឈើ​ឆ្កាង ទាំង​មើលងាយ​ចំពោះ​សេចក្តី​អាម៉ាស់​ខ្មាសនោះ ឲ្យ​តែ​បាន​សេចក្តី​អំណរ​ដែល​នៅ​ចំពោះ​ទ្រង់ រួច​ទ្រង់​ក៏​គង់​ខាង​ស្តាំ​បល្ល័ង្ក​នៃ​ព្រះ'),
  ('km', 59, 'រ៉ូម 12:15', 'ចូរ​អរ​សប្បាយ ជា​មួយ​នឹង​អ្នក​ណា​ដែល​អរ​សប្បាយ ហើយ​យំ​ជា​មួយ​នឹង​អ្នក​ណា​ដែល​យំ​ផង'),
  ('km', 60, 'សុភាសិត 1:7', 'សេចក្តី​កោតខ្លាច​ដល់​ព្រះយេហូវ៉ា នោះ​ជា​ដើម​ចម​នៃ​ដំរិះ តែ​មនុស្ស​ឥត​បើ​គិត គេ​មើលងាយ​ប្រាជ្ញា និង​សេចក្តី​ប្រៀនប្រដៅ​វិញ'),
  ('km', 61, 'អេសាយ 60:1', 'ចូរ​ក្រោក​ឡើង ហើយ​ភ្លឺ​មក​ចុះ ដ្បិត​ពន្លឺ​របស់​ឯង​បាន​មក​ដល់​ហើយ សិរីល្អ​នៃ​ព្រះយេហូវ៉ា​ក៏​បាន​រះ​ឡើង​ដល់​ឯង​ដែរ'),
  ('km', 62, 'បរិទេវ 3:22', 'គឺ​នឹក​ពី​សេចក្តី​នេះ​ថា កុំ​តែ​មាន​សេចក្តី​សប្បុរស​របស់​ព្រះយេហូវ៉ា នោះ​យើង​បាន​សូន្យ​បាត់​អស់​រលីង​ទៅ​ហើយ ឯ​សេចក្តី​មេត្តាករុណា​របស់​ទ្រង់ នោះ​មិន​ចេះ​ផុត​ឡើយ'),
  ('km', 63, 'ទំនុកដំកើង 62:1', 'ព្រលឹង​ខ្ញុំ​រង់ចាំ​ព្រះអង្គ​តែ​មួយ ដោយ​ស្ងៀម​ស្ងាត់ សេចក្តី​សង្គ្រោះ​របស់​ខ្ញុំ​ក៏​មក​តែ​ពី​ទ្រង់​ដែរ'),
  ('km', 64, 'រ៉ូម 8:28', 'តែ​យើង​ដឹង​ថា គ្រប់​ការ​ទាំង​អស់​ផ្សំ​គ្នា សំរាប់​សេចក្តី​ល្អដល់​ពួក​អ្នក​ដែល​ស្រឡាញ់​ព្រះ គឺ​ដល់​ពួក​អ្នក​ដែល​ទ្រង់​ហៅ​មក តាម​ព្រះដំរិះ​ទ្រង់'),
  ('km', 65, 'រ៉ូម 13:8', 'កុំ​ឲ្យ​ជំពាក់​អ្វី​ដល់​អ្នក​ណា​ឡើយ ជំពាក់​បាន​តែ​សេចក្តី​ស្រឡាញ់ ដល់​គ្នា​ទៅ​វិញ​ទៅ​មក​ប៉ុណ្ណោះ ដ្បិត​អ្នក​ដែល​ស្រឡាញ់​ដល់​គេ នោះ​បាន​ធ្វើ​សំរេច​តាម​ក្រឹត្យវិន័យ​ហើយ'),
  ('km', 66, 'សុភាសិត 4:23', 'ចូរ​រក្សា​ចិត្ត ដោយ​អស់​ពី​ព្យាយាម ដ្បិត​អស់​ទាំង​ផល​នៃ​ជីវិត សុទ្ធ​តែ​ចេញ​ពី​ក្នុង​ចិត្ត​មក'),
  ('km', 67, 'ហាបាគុក 2:14', 'ដ្បិត​មនុស្ស​នឹង​ស្គាល់​ដល់​សិរីល្អ​នៃ​ព្រះយេហូវ៉ា នៅ​ពេញ​លើ​ផែនដី ដូច​ជា​ទឹក​ក៏​នៅ​ពេញ​សមុទ្រ​ដែរ។'),
  ('km', 68, 'អេសាយ 40:28', 'តើ​ឯង​មិន​បាន​ដឹង តើ​មិន​បាន​ឮ​ទេ​ឬ​អី ថា​ព្រះ​ដ៏​គង់​នៅ​អស់​កល្ប​ជានិច្ច គឺ​ព្រះយេហូវ៉ា ជា​ព្រះ​ដែល​បាន​បង្កើត​ផែនដី រហូត​ដល់​ចុង​បំផុត ទ្រង់​មិន​ដែល​ល្វើយ​ឡើយ ក៏​មិន​ដែល​អស់​កំឡាំង​ផង គ្មាន​អ្នក​ណា​អាច​ស្ទង់​យល់​យោបល់​របស់​ទ្រង់​បាន​ទេ'),
  ('km', 69, 'ទំនុកដំកើង 91:1', 'អ្នក​ណា​ដែល​នៅ​ជាប់​ក្នុង​ទី​កំបាំង នៃ​ព្រះ​ដ៏​ខ្ពស់​បំផុត នោះ​នឹង​បាន​ជ្រក​នៅ​ក្រោម​ម្លប់​នៃ​ព្រះ​ដ៏​មាន​គ្រប់ ព្រះចេស្តា។'),
  ('km', 70, 'រ៉ូម 8:31', 'ដូច្នេះ យើង​នឹង​ថ្លែង​ប្រាប់​ពី​សេចក្តី​ទាំង​នេះ​ថា​ដូច​ម្តេច បើ​សិន​ជា​ព្រះ​កាន់​ខាង​យើង តើ​អ្នក​ណា​អាច​ទាស់​នឹង​យើង​បាន'),
  ('km', 71, 'រ៉ូម 15:7', 'ដូច្នេះ ចូរ​ទទួល​គ្នា​ទៅ​វិញ​ទៅ​មក ដូច​ជា​ព្រះគ្រីស្ទ​បាន​ទទួល​យើង​ដែរ សំរាប់​នឹង​សរសើរ​ដល់​ព្រះ​ចុះ។'),
  ('km', 72, 'សុភាសិត 9:10', 'សេចក្តី​កោតខ្លាច​ដល់​ព្រះយេហូវ៉ា​ជា​ដើម​ចម​នៃ​ប្រាជ្ញា ហើយ​ការ​ដែល​ស្គាល់​ដល់​ព្រះ​ដ៏​បរិសុទ្ធ​នោះ​គឺ​ជា​យោបល់'),
  ('km', 73, 'សាការី 4:6', 'នោះ​ទេវតា​ប្រាប់​មក​ខ្ញុំ​ថា នេះ​ជា​ព្រះបន្ទូល​ដែល​ព្រះយេហូវ៉ា​មាន​ព្រះបន្ទូល​ដល់​សូរ៉ូបាបិល គឺ​ព្រះយេហូវ៉ា​នៃ​ពួក​ពលបរិវារ ទ្រង់​មាន​ព្រះបន្ទូល​ថា មិន​មែន​ដោយ​ឥទ្ធិឫទ្ធិ ឬ​ដោយ​អំណាច​ទេ គឺ​ដោយសារ​វិញ្ញាណ​របស់​អញ​វិញ'),
  ('km', 74, 'អេសាយ 55:8', 'ពី​ព្រោះ​ព្រះយេហូវ៉ា​ទ្រង់​មាន​ព្រះបន្ទូល​ថា គំនិត​អញ មិន​មែន​ដូច​ជា​គំនិត​របស់​ឯង​រាល់​គ្នា​ទេ ឯ​ផ្លូវ​របស់​ឯង​រាល់​គ្នា​ក៏​មិន​មែន​ជា​ផ្លូវ​របស់​អញ​ដែរ។'),
  ('km', 75, 'ទំនុកដំកើង 121:2', 'សេចក្តី​ជំនួយ​របស់​ខ្ញុំ​មក​តែ​ពី​ព្រះយេហូវ៉ា​ទេ គឺ​ជា​ព្រះ​ដែល​បង្កើត​ផ្ទៃ​មេឃ និង​ផែនដី។'),
  ('km', 76, 'រ៉ូម 8:37', 'ទេ គឺ​ក្នុង​សេចក្តី​ទាំង​នោះ យើង​ខ្ញុំ​វិសេស​លើស​ជាង​អ្នក​ដែល​មាន​ជ័យជំនះ​ទៅ​ទៀត ដោយសារ​ព្រះអង្គ​ដែល​ទ្រង់​ស្រឡាញ់​យើង'),
  ('km', 77, 'កាឡាទី 5:13', 'បង​ប្អូន​អើយ ព្រះ​ទ្រង់​បាន​ហៅ​អ្នក​រាល់​គ្នា​មក ឲ្យ​មាន​សេរីភាព តែ​កុំ​ឲ្យ​ប្រើ​សេរី​នោះ ទុក​ជា​ឱកាស​ដល់​សាច់​ឈាម​ឡើយ គឺ​ត្រូវ​បំរើ​គ្នា​ទៅ​វិញ​ទៅ​មក ដោយ​សេចក្តី​ស្រឡាញ់​វិញ'),
  ('km', 78, 'សុភាសិត 15:1', 'ពាក្យ​តប​ឆ្លើយ​ដោយ​ស្រទន់ នោះ​រមែង​រំងាប់​សេចក្តី​ក្រោធ​ទៅ តែ​ពាក្យ​គំរោះគំរើយ នោះ​បណ្តាល​ឲ្យ​មាន​សេចក្តី​កំហឹង​វិញ។'),
  ('km', 79, 'ម៉ាថាយ 24:14', 'ដំណឹង​ល្អ​នេះ ដែល​សំដែង​ពី​នគរ នឹង​ត្រូវ​ប្រកាស​ប្រាប់​ទួទៅ​គ្រប់​ក្នុង​លោកីយ៍ ទុក​ជា​ទី​បន្ទាល់​ដល់​អស់​ទាំង​សាសន៍ នោះ​ទើប​នឹង​បាន​ដល់​ចុង​បំផុត។'),
  ('km', 80, 'អេសាយ 6:3', 'មួយ​បន្លឺ​ទៅ​កាន់​១​ថា បរិសុទ្ធ បរិសុទ្ធ គឺ​ព្រះយេហូវ៉ា​នៃ​ពួក​ពលបរិវារ​ទ្រង់​បរិសុទ្ធ ផែនដី​ទាំង​មូល​មាន​ពេញ​ដោយ​សិរីល្អ​នៃ​ទ្រង់'),
  ('km', 81, 'ទំនុកដំកើង 121:8', 'ឯ​ដំណើរ​ដែល​អ្នក​ចេញ​ចូល​ទៅ​មក នោះ​ព្រះយេហូវ៉ា​ទ្រង់​នឹង​រក្សា ចាប់​តាំង​ពី​ឥឡូវ​នេះ​រៀង​ត​ទៅ។ ទំនុកដំកើង < ១២១ >'),
  ('km', 82, 'រ៉ូម 10:17', 'ដូច្នេះ សេចក្តី​ជំនឿ​កើត​ឡើង​ដោយ​ឮ ហើយ​ដែល​ឮ​នោះ គឺ​ដោយសារ​ព្រះបន្ទូល​នៃ​ព្រះ'),
  ('km', 83, 'កាឡាទី 6:2', 'ចូរ​យក​អាសា​គ្នា​ទៅ​វិញ​ទៅ​មក យ៉ាង​នោះ ទើប​បាន​សំរេច​តាម​ក្រឹត្យវិន័យ​នៃ​ព្រះគ្រីស្ទ'),
  ('km', 84, 'សុភាសិត 22:6', 'ចូរ​បង្ហាត់​កូន​ក្មេង ឲ្យ​ប្រព្រឹត្ត​តាម​ផ្លូវ​ដែល​គួរ​ប្រព្រឹត្ត​នោះ​វា​នឹង​មិន​លះបង់​ពី​ផ្លូវ​នោះ​ដរាប​ដល់​ចាស់។'),
  ('km', 85, 'ម៉ាថាយ 28:19', 'ដូច្នេះ ចូរ​ទៅ​បញ្ចុះ​បញ្ចូល​ឲ្យ​មាន​សិស្ស​នៅ​គ្រប់​ទាំង​សាសន៍ ព្រម​ទាំង​ធ្វើ​បុណ្យ​ជ្រមុជទឹក​ឲ្យ ដោយ​នូវ​ព្រះនាម​ព្រះវរបិតា ព្រះរាជបុត្រា និង​ព្រះវិញ្ញាណ​បរិសុទ្ធ​ចុះ'),
  ('km', 86, 'ម៉ាឡាគី 3:6', 'ដ្បិត​អញ គឺ​យេហូវ៉ា អញ​មិន​ប្រែប្រួល​ឡើយ ហេតុ​នោះ ឱ​ពួក​កូន​ចៅ​យ៉ាកុបអើយ ឯង​រាល់​គ្នា​មិន​បាន​ត្រូវ​វិនាស​ទេ។'),
  ('km', 87, 'ទំនុកដំកើង 147:3', 'ទ្រង់​ប្រោស​អស់​អ្នក​ដែល​មាន​ចិត្ត​សង្រេង​ឲ្យ​បាន​ជា ក៏​រុំ​របួស​ឲ្យ​គេ​ផង'),
  ('km', 88, 'រ៉ូម 1:17', 'ដ្បិត​សេចក្តី​សុចរិត​នៃ​ព្រះ បាន​សំដែង​មក​ក្នុង​ដំណឹង​ល្អ​នោះ ដោយសារ​សេចក្តី​ជំនឿ ហើយ​ឲ្យ​បាន​សេចក្តី​ជំនឿ​ចំរើន​ច្រើន​ឡើង​ផង ដូច​មាន​សេចក្តី​ចែង​ទុក​មក​ថា «មនុស្ស​សុចរិត​នឹង​រស់​នៅ ដោយ​អាង​សេចក្តី​ជំនឿ»។'),
  ('km', 89, 'អេភេសូ 4:2', 'ព្រម​ទាំង​មាន​ចិត្ត​សុភាព ហើយ​ស្លូតបូត​គ្រប់​ជំពូក​ទាំង​អត់ធ្មត់ ហើយ​ទ្រាំ​ទ្រ​គ្នា​ទៅ​វិញ​ទៅ​មក ដោយ​ស្រឡាញ់'),
  ('km', 90, 'សាស្តា 3:1', 'មាន​ពេល​សំរាប់​គ្រប់​ទាំង​អស់ គឺ​មាន​ពេល​សំរាប់​គ្រប់​ការ ដែល​ចង់​ធ្វើ​នៅ​ក្រោម​មេឃ'),
  ('km', 91, 'ម៉ាថាយ 28:20', 'ហើយ​បង្រៀន ឲ្យ​គេ​កាន់​តាម​គ្រប់​ទាំង​សេចក្តី ដែល​ខ្ញុំ​បាន​បង្គាប់​មក​អ្នក​រាល់​គ្នា​ផង ហើយ​មើល ខ្ញុំ​ក៏​នៅ​ជា​មួយ​នឹង​អ្នក​រាល់​គ្នា​ជា​រាល់​ថ្ងៃ​ដែរ ដរាប​ដល់​បំផុត​កល្ប។ អាម៉ែន។:៚ ម៉ាថាយ < ២៨ >'),
  ('km', 92, 'យ៉ូហាន 1:14', 'ព្រះបន្ទូល​ក៏​ត្រឡប់​ជា​សាច់​ឈាម ហើយ​បាន​ស្នាក់​នៅជា​មួយ​នឹង​យើង​រាល់​គ្នា យើង​រាល់​គ្នា​បាន​ឃើញ​សិរីល្អ​ទ្រង់ គឺ​ជា​សិរីល្អ​នៃ​ព្រះរាជបុត្រា​តែ​១ ដែល​មក​ពី​ព្រះវរបិតា មាន​ពេញ​ជា​ព្រះគុណ និង​សេចក្តី​ពិត'),
  ('km', 93, 'អេសាយ 40:31', 'តែ​អស់​អ្នក​ណា​ដែល​សង្ឃឹម​ដល់​ព្រះយេហូវ៉ា​វិញ នោះ​នឹង​មាន​កំឡាំង​ចំរើន​ជានិច្ច គេ​នឹង​ហើរ​ឡើង​ទៅ​លើ ដោយ​ស្លាប ដូច​ជា​ឥន្ទ្រី គេ​នឹង​រត់​ទៅ​ឥត​ដែល​ហត់ ហើយ​នឹង​ដើរ​ឥត​ដែល​ល្វើយ​ឡើយ។ អេសាយ < ៤០ >'),
  ('km', 94, 'កាឡាទី 2:20', 'ខ្ញុំ​បាន​ជាប់​ឆ្កាង​ជា​មួយ​នឹង​ព្រះគ្រីស្ទ ប៉ុន្តែ​ខ្ញុំ​រស់​នៅ មិន​មែន​ជា​ខ្ញុំ​ទៀត គឺ​ជា​ព្រះគ្រីស្ទ​ទ្រង់​រស់​ក្នុង​ខ្ញុំ​វិញ ហើយ​ដែល​ខ្ញុំ​រស់​ក្នុង​សាច់​ឈាម​ឥឡូវ​នេះ នោះ​គឺ​រស់​ដោយ​សេចក្តី​ជំនឿ ជឿ​ដល់​ព្រះរាជបុត្រា​នៃ​ព្រះ ដែល​ទ្រង់​ស្រឡាញ់​ខ្ញុំ ក៏​បាន​ប្រគល់​ព្រះអង្គ​ទ្រង់​ជំនួស​ខ្ញុំ​ហើយ'),
  ('km', 95, 'អេភេសូ 4:32', 'ចូរ​មាន​ចិត្ត​សប្បុរស​នឹង​គ្នា​ទៅ​វិញ​ទៅ​មក ព្រម​ទាំង​មាន​ចិត្ត​ទន់​សន្តោស ហើយ​អត់​ទោស​គ្នា ដូច​ជា​ព្រះ​ទ្រង់​បាន​អត់​ទោស​ឲ្យ​អ្នក​រាល់​គ្នា ដោយ​ព្រះគ្រីស្ទ​ដែរ។ អេភេសូ < ៤ >'),
  ('km', 96, 'សាស្តា 12:13', 'សេចក្តី​នេះ​ចប់​តែ​ប៉ុណ្ណោះ ទាំង​អស់​បាន​សំដែង​ទុក​ហើយ ដូច្នេះ ចូរ​កោតខ្លាច​ដល់​ព្រះ ហើយ​កាន់​តាម​បញ្ញត្ត​ទ្រង់​ចុះ ដ្បិត​ប៉ុណ្ណេះ​ឯង​ជា​កិច្ច​ទាំង​មូល​ដែល​មនុស្ស​ត្រូវ​ធ្វើ'),
  ('km', 97, 'ម៉ាកុស 16:15', 'ទ្រង់​ផ្តាំ​គេ​ថា ចូរ​អ្នក​រាល់​គ្នា​ទៅ​ពេញ​សព្វ​ក្នុង​លោកីយ៍​ទាំង​មូល ហើយ​ផ្សាយ​ដំណឹង​ល្អ​ទួទៅ​ដល់​គ្រប់​មនុស្ស​ទាំង​អស់​ចុះ'),
  ('km', 98, 'យ៉ូហាន 3:16', 'ដ្បិត​ព្រះ​ទ្រង់​ស្រឡាញ់​មនុស្ស​លោក ដល់​ម៉្លេះ​បាន​ជា​ទ្រង់​ប្រទាន​ព្រះរាជបុត្រា​ទ្រង់​តែ​១ ដើម្បី​ឲ្យ​អ្នក​ណា​ដែល​ជឿ​ដល់​ព្រះរាជបុត្រា​នោះ មិន​ត្រូវ​វិនាស​ឡើយ គឺ​ឲ្យ​មាន​ជីវិត​អស់​កល្ប​ជានិច្ច​វិញ'),
  ('km', 99, 'អេសាយ 41:10', 'កុំ​ឲ្យ​ភ័យ​ខ្លាច​ឡើយ ដ្បិត​អញ​នៅ​ជា​មួយ​នឹង​ឯង កុំ​ឲ្យ​ស្រយុត​ចិត្ត​ឲ្យ​សោះ ពី​ព្រោះ​អញ​ជា​ព្រះ​នៃ​ឯង អញ​នឹង​ចំរើន​កំឡាំង​ដល់​ឯង អើ អញ​នឹង​ជួយ​ឯង អើ អញ​នឹង​ទ្រ​ឯង ដោយ​ដៃ​ស្តាំ​ដ៏​សុចរិត​របស់​អញ'),
  ('km', 100, 'អេភេសូ 2:8', 'ដ្បិត​គឺ​ដោយ​ព្រះគុណ ដែល​អ្នក​រាល់​គ្នា​បាន​សង្គ្រោះ ដោយសារ​សេចក្តី​ជំនឿ ហើយ​សេចក្តី​នោះ​ក៏​មិន​មែន​កើត​ពី​អ្នក​រាល់​គ្នា​ដែរ គឺ​ជា​អំណោយ​ទាន​របស់​ព្រះ​វិញ'),
  ('km', 101, 'កូឡូស 3:13', 'ហើយ​ទ្រាំ​ទ្រ​គ្នា ទាំង​អត់​ទោស​ទៅ​វិញ​ទៅ​មក បើ​អ្នក​ណា​មាន​ហេតុ​ទាស់​នឹង​អ្នក​ណា នោះ​ចូរ​អត់​ទោស​ឲ្យ​គេ​ចុះ ដូច​ជា​ព្រះគ្រីស្ទ​បាន​អត់​ទោស​ឲ្យ​អ្នក​រាល់​គ្នា​ដែរ'),
  ('km', 102, 'ម៉ាថាយ 5:14', 'អ្នក​រាល់​គ្នា​ជា​ពន្លឺ​នៃ​លោកីយ៍ ឯ​ទី​ក្រុង​ណា​ដែល​នៅ​លើ​ភ្នំ នោះ​លាក់​មិន​កំបាំង​ទេ'),
  ('km', 103, 'កិច្ចការ 1:8', 'ប៉ុន្តែ កាល​ណា​ព្រះវិញ្ញាណ​បរិសុទ្ធ​បាន​មក​សណ្ឋិត​លើ​អ្នក​រាល់​គ្នា នោះ​អ្នក​រាល់​គ្នា​នឹង​បាន​ព្រះចេស្តា ហើយ​និង​ធ្វើ​ជា​ទី​បន្ទាល់​ពី​ខ្ញុំ នៅ​ក្រុង​យេរូសាឡិម ព្រម​ទាំង​ស្រុក​យូដា និង​ស្រុក​សាម៉ារី​ទាំង​មូល ហើយ​រហូត​ដល់​ចុង​ផែនដី​បំផុត​ផង'),
  ('km', 104, 'យ៉ូហាន 4:24', 'ឯ​ព្រះ ទ្រង់​ជា​វិញ្ញាណ ហើយ​អ្នក​ណា​ដែល​ថ្វាយ​បង្គំ​ទ្រង់ នោះ​ត្រូវ​តែ​ថ្វាយ​បង្គំ ដោយ​វិញ្ញាណ និង​សេចក្តី​ពិត​ដែរ'),
  ('km', 105, 'អេសាយ 43:2', 'កាល​ណា​ឯង​ដើរ​កាត់​ទឹក​ធំ នោះ​អញ​នឹង​នៅ​ជា​មួយ កាល​ណា​ដើរ​កាត់​ទន្លេ នោះ​ទឹក​នឹង​មិន​លិច​ឯង​ឡើយ កាល​ណា​ឯង​លុយ​កាត់​ភ្លើង នោះ​ឯង​នឹង​មិន​ត្រូវ​រលាក ហើយ​អណ្តាត​ភ្លើង​ក៏​មិន​ឆាប់​ឆេះ​ឯង​ដែរ'),
  ('km', 106, 'ម៉ាកុស 9:23', 'ព្រះយេស៊ូវ​មាន​ព្រះបន្ទូល​ទៅ​គាត់​ថា បើ​អាច​នឹង​ជឿ​បាន នោះ​ការ​ទាំង​អស់​នឹង​សំរេច​បាន ដល់​អ្នក​ណា​ដែល​ជឿ'),
  ('km', 107, 'កូឡូស 3:14', 'ចូរ​បន្ថែម​ទាំង​សេចក្តី​ស្រឡាញ់​ថែម​ទៀត ជា​ចំណង​នៃ​សេចក្តី​គ្រប់​លក្ខណ៍'),
  ('km', 108, 'ម៉ាថាយ 5:16', 'ដូច្នេះ ចូរ​ឲ្យ​ពន្លឺ​របស់​អ្នក​រាល់​គ្នា បាន​ភ្លឺ​នៅ​មុខ​មនុស្ស​លោក​យ៉ាង​នោះ​ដែរ ដើម្បី​ឲ្យ​គេ​ឃើញ​ការ​ល្អ ដែល​អ្នក​រាល់​គ្នា​ប្រព្រឹត្ត រួច​សរសើរដំកើង ដល់​ព្រះវរបិតា​នៃ​អ្នក​រាល់​គ្នា​ដែល​គង់​នៅ​ស្ថានសួគ៌។'),
  ('km', 109, 'កិច្ចការ 20:24', 'ប៉ុន្តែ នោះ​មិន​អំពល់​អ្វី​ដល់​ខ្ញុំ​ទេ ខ្ញុំ​ក៏​មិន​រាប់​ជីវិត​នេះ ទុក​ជា​របស់​វិសេស​ដល់​ខ្ញុំ​ដែរ ឲ្យ​តែ​ខ្ញុំ​បាន​បង្ហើយ​ការ​រត់​ប្រណាំង​របស់​ខ្ញុំ ដោយ​អំណរ​ចុះ ព្រម​ទាំង​ការងារ ដែល​ខ្ញុំ​បាន​ទទួល​អំពី​ព្រះអម្ចាស់យេស៊ូវ គឺ​ឲ្យ​ខ្ញុំ​បាន​ធ្វើ​បន្ទាល់​សព្វ​គ្រប់ ពី​ដំណឹង​ល្អ​នៃ​ព្រះគុណ​ព្រះ​វិញ'),
  ('km', 110, 'យ៉ូហាន 10:11', 'ខ្ញុំ​ជា​អ្នក​គង្វាល​ល្អ ឯ​អ្នក​គង្វាល​ល្អ ក៏​ស៊ូ​តែ​ប្តូរ​ជីវិត​ជំនួស​ចៀម'),
  ('km', 111, 'យេរេមា 29:11', 'ដ្បិត​ព្រះយេហូវ៉ា​ទ្រង់​មាន​ព្រះបន្ទូល​ថា អញ​ស្គាល់​សេចក្តី​ដែល​អញ​គិត​ពី​ដំណើរ​ឯង​រាល់​គ្នា មិន​មែន​គិត​ធ្វើ​សេចក្តី​អាក្រក់​ទេ គឺ​គិត​ឲ្យ​បាន​សេចក្តី​សុខ​វិញ ដើម្បី​ដល់​ចុង​បំផុត ឲ្យ​ឯង​រាល់​គ្នា​បាន​សេចក្តី​សង្ឃឹម'),
  ('km', 112, 'ម៉ាកុស 11:24', 'ដោយ​ហេតុ​នោះ​បាន​ជា​ខ្ញុំ​ប្រាប់​អ្នក​រាល់​គ្នា​ថា គ្រប់​ទាំង​សេចក្តី​ដែល​អ្នក​រាល់​គ្នា​អធិស្ឋាន​សូម ចូរ​ជឿ​ថា បាន​ហើយ នោះ​នឹង​បាន​មែន'),
  ('km', 113, 'ភីលីព 2:3', 'កុំ​ឲ្យ​ធ្វើ​អ្វី ដោយ​ទាស់ទែង​គ្នា ឬ​ដោយ​សេចក្តី​អំនួត​ឥត​ប្រយោជន៍​ឡើយ តែ​ចូរ​រាប់​អាន​គេ​ឲ្យ​លើស​ជាង​ខ្លួន​ដោយ​ចិត្ត​សុភាព​វិញ'),
  ('km', 114, 'ម៉ាថាយ 7:12', 'ដូច្នេះ អស់​ទាំង​ការ​អ្វី ដែល​អ្នក​រាល់​គ្នា​ចង់​ឲ្យ​មនុស្ស​លោក​ប្រព្រឹត្ត​នឹង​ខ្លួន នោះ​ត្រូវ​ឲ្យ​អ្នក​ប្រព្រឹត្ត​នឹង​គេ​ដូច្នោះ​ដែរ ដ្បិត​នេះ​ឯង​ជា​ក្រឹត្យវិន័យ ហើយ​ជា​សេចក្តី​ទំនាយ​របស់​ពួក​ហោរា។'),
  ('km', 115, 'រ៉ូម 1:16', 'ដ្បិត​ខ្ញុំ​គ្មាន​សេចក្តី​ខ្មាស ចំពោះ​ដំណឹង​ល្អ​នៃ​ព្រះគ្រីស្ទ​ទេ ពី​ព្រោះ​ជា​ព្រះចេស្តា​នៃ​ព្រះ សំរាប់​នឹង​ជួយ​សង្គ្រោះ​ដល់​អស់​អ្នក​ណា​ដែល​ជឿ គឺ​ដល់​ទាំង​សាសន៍​យូដា​ជា​ដើម និង​សាសន៍​ក្រេក​ផង'),
  ('km', 116, 'យ៉ូហាន 11:25', 'ព្រះយេស៊ូវ​មាន​ព្រះបន្ទូល​ទៅ​នាង​ថា ខ្ញុំ​ជា​សេចក្តី​រស់​ឡើង​វិញ ហើយ​ជា​ជីវិត អ្នក​ណា​ដែល​ជឿ​ដល់​ខ្ញុំ ទោះ​បើ​បាន​ស្លាប់​ហើយ គង់​តែ​នឹង​រស់​ឡើង​វិញ​ដែរ'),
  ('km', 117, 'ម៉ាថាយ 11:28', 'អស់​អ្នក​ដែល​នឿយ​ព្រួយ ហើយ​ផ្ទុក​ធ្ងន់​អើយ ចូរ​មក​ឯ​ខ្ញុំ ខ្ញុំ​នឹង​ឲ្យ​អ្នក​រាល់​គ្នា​ឈប់​សំរាក'),
  ('km', 118, 'ម៉ាថាយ 6:33', 'ចូរ​ស្វែង​រក​នគរ និង​សេចក្តី​សុចរិត​នៃ​ព្រះ​ជា​មុន​សិន ទើប​គ្រប់​របស់​ទាំង​នោះ នឹង​បាន​ប្រទាន​មក​អ្នក​រាល់​គ្នា​ថែម​ទៀត​ផង'),
  ('km', 119, 'ភីលីព 2:4', 'កុំ​ឲ្យ​គ្រប់​គ្នា​ស្វែង​រក​តែ​ប្រយោជន៍​ផ្ទាល់​ខ្លួន​ឡើយ ត្រូវ​ស្វែង​រក​ចំពោះ​អ្នក​ដទៃ​ផង'),
  ('km', 120, 'ម៉ាថាយ 22:37', 'នោះ​ព្រះយេស៊ូវ​ឆ្លើយ​ថា «ត្រូវ​ឲ្យ​ស្រឡាញ់​ព្រះអម្ចាស់ ជា​ព្រះ​នៃ​ឯង​ឲ្យ​អស់​អំពី​ចិត្ត អស់​អំពី​ព្រលឹង ហើយ​អស់​អំពី​គំនិត​ឯង»'),
  ('km', 121, 'រ៉ូម 10:15', 'មួយ​ទៀត ធ្វើ​ដូច​ម្តេច​ឲ្យ​មាន​អ្នក​ណា​ប្រាប់​បាន លើក​តែ​មាន​អ្នក​ណា​ចាត់​ឲ្យ​គេ​ទៅ ដូច​ជា​មាន​សេចក្តី​ចែង​ទុក​មក​ថា «ជើង​នៃ​ពួក​អ្នក ដែល​ប្រកាស​ប្រាប់​ដំណឹង​ល្អ ពី​សេចក្តី​សុខ​សាន្ត ហើយ​ថ្លែង​ប្រាប់​ពី​សេចក្តី​ដែល​បណ្តាល​ឲ្យ​រីករាយ​ចិត្ត នោះ​ល្អ​ប្រពៃ​យ៉ាង​ណា​ហ្ន៎»។'),
  ('km', 122, 'យ៉ូហាន 14:6', 'ព្រះយេស៊ូវ​មាន​ព្រះបន្ទូល​ទៅ​គាត់​ថា ខ្ញុំ​ជា​ផ្លូវ ជា​សេចក្តី​ពិត ហើយ​ជា​ជីវិត បើ​មិន​មក​តាម​ខ្ញុំ នោះ​គ្មាន​អ្នក​ណា​ទៅ​ឯ​ព្រះវរបិតា​បាន​ឡើយ'),
  ('km', 123, 'យ៉ូហាន 14:27', 'ខ្ញុំ​ទុក​សេចក្តី​សុខ​នៅ​នឹង​អ្នក​រាល់​គ្នា គឺ​ខ្ញុំ​ឲ្យ​សេចក្តី​សុខ​សាន្ត​របស់​ខ្ញុំ​ដល់​អ្នក​រាល់​គ្នា ហើយ​ដែល​ខ្ញុំ​ឲ្យ នោះ​មិន​មែន​ដូច​ជា​លោកីយ៍​ឲ្យ​ទេ កុំ​ឲ្យ​ចិត្ត​អ្នក​រាល់​គ្នា​ថប់​បារម្ភ ឬ​ភ័យ​ឡើយ'),
  ('km', 124, 'ម៉ាថាយ 6:34', 'ដូច្នេះ កុំ​ឲ្យ​ខ្វល់ខ្វាយ​នឹង​ថ្ងៃ​ស្អែក​ឡើយ ពី​ព្រោះ​ថ្ងៃ​ស្អែក​នឹង​ខ្វល់ខ្វាយ ចំពោះ​ការ​របស់​ថ្ងៃ​នោះ​ឯង សេចក្តី​លំបាក​នៅ​ថ្ងៃ​ណា នោះ​គឺ​ល្មម​ត្រឹម​ថ្ងៃ​នោះ​ហើយ។ ម៉ាថាយ < ៦ >'),
  ('km', 125, 'ហេព្រើរ 10:24', 'ហើយ​ត្រូវ​ឲ្យ​យើង​ពិចារណា​មើល​គ្នា​ទៅ​វិញ​ទៅ​មក​ដែរ ដើម្បី​នឹង​បណ្តាល​ឲ្យ​មាន​សេចក្តី​ស្រឡាញ់ ហើយ​ឲ្យ​ប្រព្រឹត្ត​ការ​ល្អ​ផង'),
  ('km', 126, 'លូកា 9:23', 'រួច​ទ្រង់​មាន​ព្រះបន្ទូល​ទៅ​មនុស្ស​ទាំង​អស់​ថា បើ​អ្នក​ណា​ចង់​មក​តាម​ខ្ញុំ ត្រូវ​ឲ្យ​អ្នក​នោះ​លះ​កាត់​ចិត្ត​ខ្លួន​ឯង ទាំង​ផ្ទុក​ឈើ​ឆ្កាង​ខ្លួន​រាល់​តែ​ថ្ងៃ ហើយ​មក​តាម​ខ្ញុំ​ចុះ'),
  ('km', 127, 'រ៉ូម 15:13', 'ឥឡូវ​នេះ សូម​ព្រះ​នៃ​សេចក្តី​សង្ឃឹម​ប្រទាន​ឲ្យ​អ្នក​រាល់​គ្នា​បាន​គ្រប់​អស់​ទាំង​សេចក្តី​អំណរ និង​សេចក្តី​សុខ​សាន្ត​ដ៏​ពោរពេញ ដោយសារ​សេចក្តី​ជំនឿ ប្រយោជន៍​ឲ្យ​បាន​សេចក្តី​សង្ឃឹម​ជា​បរិបូរ ដោយ​ព្រះចេស្តា​នៃ​ព្រះវិញ្ញាណ​បរិសុទ្ធ។'),
  ('km', 128, 'រ៉ូម 5:8', 'តែ​ឯ​ព្រះ ទ្រង់​សំដែង​សេចក្តី​ស្រឡាញ់​របស់​ទ្រង់ ដល់​យើង​រាល់​គ្នា​ឲ្យ​ឃើញ​ច្បាស់ ដោយ​ព្រះគ្រីស្ទ​បាន​សុគត​ជំនួស​យើង​រាល់​គ្នា នោះ​គឺ​ក្នុង​កាល​ដែល​យើង​នៅ​មាន​បាប​នៅ​ឡើយ​ផង'),
  ('km', 129, 'យ៉ូហាន 16:33', 'ខ្ញុំ​ប្រាប់​សេចក្តី​ទាំង​នេះ ដើម្បី​ឲ្យ​អ្នក​រាល់​គ្នា បាន​សេចក្តី​សុខ​សាន្ត ដោយសារ​ខ្ញុំ នៅ​លោកីយ៍​នេះ នោះ​អ្នក​រាល់​គ្នា​មាន​សេចក្តី​វេទនា​មែន ប៉ុន្តែ ត្រូវ​សង្ឃឹម​ឡើង ដ្បិត​ខ្ញុំ​បាន​ឈ្នះ​លោកីយ៍​ហើយ។ យ៉ូហាន < ១៦ >'),
  ('km', 130, 'ម៉ាថាយ 7:7', 'ចូរ​សូម នោះ​តែង​នឹង​ឲ្យ​មក​អ្នក ចូរ​រក នោះ​តែង​នឹង​ឃើញ ចូរ​គោះ នោះ​តែង​នឹង​បើក​ឲ្យ​អ្នក'),
  ('km', 131, 'ហេព្រើរ 10:25', 'ឥត​លែង​ប្រជុំ​គ្នា ដូច​ជា​អ្នក​ខ្លះ​ធ្លាប់​នោះ​ឡើយ ត្រូវ​ឲ្យ​កំឡា​ចិត្ត​គ្នា​វិញ ឲ្យ​កាន់​តែ​ខ្លាំង​ឡើង​ផង តាម​ដែល​ឃើញ​ថា​ថ្ងៃ​នោះ​ជិត​មក​ដល់​ហើយ'),
  ('km', 132, 'រ៉ូម 12:1', 'ដូច្នេះ បង​ប្អូន​អើយ ខ្ញុំ​ទូន្មាន​អ្នក​រាល់​គ្នា ដោយ​សេចក្តី​មេត្តាករុណា​នៃ​ព្រះ ឲ្យ​បាន​ថ្វាយ​រូបកាយ​ទុក​ជា​យញ្ញបូជា​រស់ ហើយ​បរិសុទ្ធ ដែល​គាប់​ព្រះហឫទ័យ​ដល់​ព្រះ ជា​ការ​គោរព​នៃ​អ្នក​រាល់​គ្នា ដែល​មាន​ទំនង'),
  ('km', 133, 'កូរិនថូសទី ២ 4:16', 'ហេតុ​នោះ​យើង​ខ្ញុំ​មិន​ណាយ​ចិត្ត​ឡើយ ប៉ុន្តែ ទោះ​បើ​មនុស្ស​ខាង​ក្រៅ​របស់​យើង​ខ្ញុំ កំពុង​តែ​ពុករលួយ​ទៅ​ក៏​ពិត​មែន តែ​នៅ​ខាង​ក្នុងកំពុង​តែ​កែ​ប្រែ​ជា​ថ្មី​ឡើង​រាល់​ថ្ងៃ​ជានិច្ច​វិញ'),
  ('km', 134, 'រ៉ូម 11:36', 'ដ្បិត​របស់​សព្វ​សារពើ​បាន​កើត​មក​ពី​ទ្រង់ ដោយសារ​ទ្រង់ ហើយ​សំរាប់​ទ្រង់ សូម​ឲ្យ​ទ្រង់​បាន​សិរីល្អ​នៅ​អស់​កល្ប​ជានិច្ច អាម៉ែន។ រ៉ូម < ១១ >'),
  ('km', 135, 'កូរិនថូសទី ២ 12:9', 'តែ​ទ្រង់​មាន​ព្រះបន្ទូល​មក​ខ្ញុំ​ថា គុណ​របស់​អញ​ល្មម​ដល់​ឯង​ហើយ ដ្បិត​កំឡាំង​អញ​បាន​ពេញ​ខ្នាត ដោយ​សេចក្តី​កំសោយ ដូច្នេះ ខ្ញុំ​នឹង​ស៊ូ​អួត​ពី​សេចក្តី​កំសោយ​របស់​ខ្ញុំ ដោយ​អំណរ​ជា​ខ្លាំង ដើម្បី​ឲ្យ​ព្រះចេស្តា​នៃ​ព្រះគ្រីស្ទ​បាន​សណ្ឋិត​នៅ​នឹង​ខ្ញុំ'),
  ('km', 136, 'ភីលីព 4:13', 'ខ្ញុំ​អាច​នឹង​ធ្វើ​គ្រប់​ទាំង​អស់​បាន ដោយសារ​ព្រះគ្រីស្ទ​ដែល​ទ្រង់​ចំរើន​កំឡាំង​ដល់​ខ្ញុំ'),
  ('km', 137, 'ពេត្រុស​ទី​១ 4:8', 'តែ​មុន​ដំបូង​បង្អស់ ត្រូវ​ឲ្យ​អ្នក​រាល់​គ្នា​មាន​សេចក្តី​ស្រឡាញ់​គ្នា ឲ្យ​អស់​ពី​ចិត្ត ដ្បិត​សេចក្តី​ស្រឡាញ់​នឹង​គ្រប​បាំង​អំពើ​បាប​ជា​អនេកអនន្ត'),
  ('km', 138, 'រ៉ូម 12:2', 'កុំ​ឲ្យ​ត្រាប់​តាម​សម័យ​នេះ​ឡើយ ចូរ​ឲ្យ​អ្នក​រាល់​គ្នា​បាន​ផ្លាស់​ប្រែ​វិញ ដោយ​គំនិត​បាន​កែ​ជា​ថ្មី​ឡើង ដើម្បី​នឹង​អាច​ល​មើល​ឲ្យ​បាន​ស្គាល់​បំណង​ព្រះហឫទ័យ​នៃ​ព្រះ ដែល​ល្អ ស្រួល​ទទួល ហើយ​គ្រប់​លក្ខណ៍​ផង'),
  ('km', 139, 'កូរិនថូសទី ២ 4:18', 'ដោយ​យើង​ខ្ញុំ​មិន​រាប់​អាន​របស់​ដែល​មើល​ឃើញ​ឡើយ គឺ​រាប់​អាន​តែ​របស់​ដែល​មើល​មិន​ឃើញ​វិញ ដ្បិត​របស់​ដែល​មើល​ឃើញ នោះ​ស្ថិតស្ថេរ​មិន​យូរ​ប៉ុន្មាន​ទេ តែ​ឯ​របស់​ដែល​មើល​មិន​ឃើញ នោះ​នៅ​ស្ថិតស្ថេរ​អស់​កល្ប​ជានិច្ច​វិញ។ កូរិនថូសទី ២ < ៤ >'),
  ('km', 140, 'យ៉ូហាន​ទី​១ 4:8', 'តែ​អ្នក​ណា​ដែល​គ្មាន​សេចក្តី​ស្រឡាញ់ នោះ​មិន​ស្គាល់​ព្រះ​វិញ ពី​ព្រោះ​ព្រះ​ទ្រង់​ជា​សេចក្តី​ស្រឡាញ់​នោះ​ឯង'),
  ('km', 141, 'ពេត្រុស​ទី​១ 5:7', 'ហើយ​ចូរ​ផ្ទេរ​គ្រប់​ទាំង​សេចក្តី​ទុក្ខ​ព្រួយ​របស់​អ្នក​រាល់​គ្នា​ទៅ​លើ​ទ្រង់ ដ្បិត​ទ្រង់​តែង​យក​ព្រះទ័យ​ទុក​ដាក់​នឹង​អ្នក​រាល់​គ្នា។'),
  ('km', 142, 'ភីលីព 1:6', 'ខ្ញុំ​ជឿ​សេចក្តី​នេះ​ជា​យ៉ាង​ជាក់​ថា ព្រះអង្គ​ដែល​ទ្រង់​បាន​ចាប់​តាំង​ធ្វើ​ការ​ល្អ​ក្នុង​អ្នក​រាល់​គ្នា ទ្រង់​នឹង​ធ្វើ​ឲ្យ​កាន់​តែ​ពេញ​ខ្នាត​ឡើង ទាល់​តែ​ដល់​ថ្ងៃ​នៃ​ព្រះយេស៊ូវគ្រីស្ទ'),
  ('km', 143, 'យ៉ូហាន​ទី​១ 3:18', 'ពួក​កូន​តូចៗ អើយ យើង​មិន​ត្រូវ​ស្រឡាញ់ ដោយ​ពាក្យ​សំដី ឬ​ដោយ​បបូរ​មាត់​ប៉ុណ្ណោះ​ឡើយ គឺ​ដោយ​ការ​ប្រព្រឹត្ត និង​សេចក្តី​ពិត​វិញ'),
  ('km', 144, 'រ៉ូម 12:12', 'ចូរ​អរ​សប្បាយ ដោយ​មាន​សង្ឃឹម ចូរ​អត់​ធន់​ក្នុង​សេចក្តី​ទុក្ខ​លំបាក ចូរ​ឲ្យ​ខ្ជាប់ខ្ជួន​ក្នុង​សេចក្តី​អធិស្ឋាន'),
  ('km', 145, 'កូរិនថូសទី ២ 5:20', 'ដូច្នេះ យើង​ខ្ញុំ​ជា​ទូត​ដំណាង​ព្រះគ្រីស្ទ ហាក់​ដូច​ជា​ព្រះ​ទ្រង់​អង្វរ​ដោយសារ​យើង​ខ្ញុំ គឺ​យើង​ខ្ញុំ​អង្វរ​គេ​ជំនួស​ព្រះគ្រីស្ទ​ថា ចូរ​ឲ្យ​បាន​ជា​មេត្រី​នឹង​ព្រះ​ចុះ'),
  ('km', 146, 'យ៉ាកុប 1:17', 'គ្រប់​ទាំង​របស់​ដ៏​ល្អ ដែល​ព្រះ​ប្រទាន​មក និង​អស់​ទាំង​អំណោយ​ទាន​ដ៏​គ្រប់​លក្ខណ៍ នោះ​សុទ្ធ​តែ​មក​ពី​ស្ថាន​លើ គឺ​មក​ពី​ព្រះវរបិតា​នៃ​ពន្លឺ ដែល​ទ្រង់​មិន​ចេះ​ប្រែប្រួល សូម្បី​តែ​ស្រមោល​នៃ​សេចក្តី​ផ្លាស់​ប្រែ​ក៏​គ្មាន​ដែរ'),
  ('km', 147, 'ភីលីព 4:6', 'កុំ​ឲ្យ​ខ្វល់ខ្វាយ​អ្វី​ឡើយ ចូរ​ទូល​ដល់​ព្រះ ឲ្យ​ជ្រាប​ពី​សេចក្តី​សំណូម​របស់​អ្នក​រាល់​គ្នា​ក្នុង​គ្រប់​ការ​ទាំង​អស់ ដោយ​សេចក្តី​អធិស្ឋាន និង​ពាក្យ​ទូល​អង្វរ ទាំង​ពោល​ពាក្យ​អរ​ព្រះគុណ​ផង'),
  ('km', 148, 'កូរិនថូសទី ២ 5:7', 'ដ្បិត​យើង​ខ្ញុំ​ដើរ​ដោយ​ជំនឿ មិន​មែន​ដោយ​មើល​ឃើញ​ទេ'),
  ('km', 149, 'យ៉ូហាន​ទី​១ 4:7', 'ពួក​ស្ងួនភ្ងា​អើយ យើង​ត្រូវ​ស្រឡាញ់​គ្នា​ទៅ​វិញ​ទៅ​មក ដ្បិត​សេចក្តី​ស្រឡាញ់​មក​ពី​ព្រះ ឯ​អស់​អ្នក​ណា​ដែល​មាន​សេចក្តី​ស្រឡាញ់ នោះ​ឈ្មោះ​ថា​មក​ពី​ព្រះ ហើយ​ក៏​ស្គាល់​ទ្រង់​ដែរ'),
  ('km', 150, 'រ៉ូម 12:21', 'កុំ​ឲ្យ​សេចក្តី​អាក្រក់​ឈ្នះ​អ្នក​ឡើយ ត្រូវ​ឲ្យ​អ្នក​ឈ្នះ​សេចក្តី​អាក្រក់ ដោយសារ​សេចក្តី​ល្អ​វិញ។ រ៉ូម < ១២ >'),
  ('km', 151, 'អេភេសូ 3:20', 'ឯ​ព្រះ​ដែល​ទ្រង់​អាច​នឹង​ធ្វើ​ហួស​សន្ធឹក លើស​ជាង​អស់​ទាំង​សេចក្តី​ដែល​យើង​សូម ឬ​គិត​ក្តី តាម​ព្រះចេស្តា ដែល​បណ្តាល​ក្នុង​យើង​រាល់​គ្នា'),
  ('km', 152, 'ហេព្រើរ 13:8', 'ដ្បិត​ព្រះយេស៊ូវគ្រីស្ទ​ទ្រង់​នៅ​តែ​ដដែល គឺ​ពី​ថ្ងៃ​ម្សិល ថ្ងៃ​នេះ ហើយ​ទៅ​ដល់​អស់​កល្ប​ជានិច្ច​ត​ទៅ'),
  ('km', 153, 'វិវរណៈ 21:4', 'ព្រះ​ទ្រង់​នឹង​ជូត​អស់​ទាំង​ទឹក​ភ្នែក ពី​ភ្នែក​គេ​ចេញ និង​គ្មាន​សេចក្តី​ស្លាប់ ឬ​សេចក្តី​សោក​សង្រេង ឬ​សេចក្តី​យំ​ទួញ ឬ​ទុក្ខ​លំបាក​ណា​ទៀត​ឡើយ ដ្បិត​សេចក្តី​មុន​ទាំង​ប៉ុន្មាន បាន​កន្លង​បាត់​ទៅ​ហើយ។'),
  ('km', 154, 'យ៉ូហាន 20:29', 'ព្រះយេស៊ូវ​មាន​ព្រះបន្ទូល​ទៅ​គាត់​ថា ថូម៉ាស​អើយ អ្នក​ជឿ​ដោយ​ព្រោះ​បាន​ឃើញ​ខ្ញុំ​ទេ​តើ មាន​ពរ​ហើយ អ្នក​ណា​ដែល​ជឿ​ឥត​ឃើញ​សោះ។'),
  ('km', 155, 'យ៉ូហាន​ទី​១ 4:19', 'ឯ​យើង​រាល់​គ្នា យើង​ស្រឡាញ់​ទ្រង់ ពី​ព្រោះ​ទ្រង់​បាន​ស្រឡាញ់​យើង​ជា​មុន។'),
  ('km', 156, 'កូរិនថូសទី ១ 10:31', 'ដូច្នេះ ទោះ​បើ​ស៊ី ឬ​ផឹក ឬ​ធ្វើ​ការ​អ្វី​ក៏​ដោយ នោះ​ចូរ​ធ្វើ​ទាំង​អស់​សំរាប់​ចំរើន​សិរីល្អ​ដល់​ព្រះ​ចុះ'),
  ('km', 157, 'ភីលីព 3:14', 'ទាំង​រត់​ដំរង់​ទៅ​ឯ​ទី ដើម្បី​ឲ្យ​បាន​រង្វាន់​នៃ​ការងារ​ដ៏​ខ្ពស់​របស់​ព្រះ ក្នុង​ព្រះគ្រីស្ទយេស៊ូវ'),
  ('km', 158, 'វិវរណៈ 1:8', 'ព្រះអម្ចាស់​ដ៏​ជា​ព្រះ ដែល​ទ្រង់​គង់​នៅ ក៏​គង់​នៅ​តាំង​តែ​ពី​ដើម ហើយ​ត្រូវ​យាង​មក​ទៀត គឺ​ជា​ព្រះ​ដ៏​មាន​ព្រះចេស្តា​បំផុត ទ្រង់​មាន​ព្រះបន្ទូល​ថា អញ​ជា​អាលផា និង​ជា​អូមេកា គឺ​ជា​ដើម ហើយ​ជា​ចុង។'),
  ('km', 159, 'យ៉ាកុប 1:5', 'តែ​បើ​អ្នក​រាល់​គ្នា​ណា​មួយ​ខ្វះ​ប្រាជ្ញា មាន​តែ​សូម​ដល់​ព្រះ ដែល​ទ្រង់​ប្រទាន​ដល់​មនុស្ស​ទាំង​អស់​ដោយ​សទ្ធា ឥត​បន្ទោស​ផង នោះ​ទ្រង់​នឹង​ប្រទាន​ឲ្យ'),
  ('km', 160, 'សាស្តា 4:12', 'ហើយ​បើ​មាន​ខ្មាំង​ណា​មក ដែល​មាន​កំឡាំង​ជាង នោះ​២​នាក់​នឹង​អាច​ទប់​ទល់​បាន ឯ​ពួរ​៣​ធ្លុង​មិន​ងាយ​ដាច់​ទេ។'),
  ('km', 161, 'កូរិនថូសទី ២ 5:17', 'បាន​ជា​បើ​អ្នក​ណា​នៅ​ក្នុង​ព្រះគ្រីស្ទ នោះ​ឈ្មោះ​ថា​បាន​កើត​ជា​ថ្មី​ហើយ អស់​ទាំង​សេចក្តី​ចាស់​បាន​កន្លង​បាត់​ទៅ មើល គ្រប់​ទាំង​អស់​បាន​ត្រឡប់​ជា​ថ្មី​វិញ'),
  ('km', 162, 'ភីលីព 3:20', 'ឯ​យើង​រាល់​គ្នា យើង​ជា​សាសន៍​ស្ថានសួគ៌​វិញ ក៏​នៅ​ចាំ​ព្រះអម្ចាស់យេស៊ូវគ្រីស្ទ ជា​ព្រះអង្គ​សង្គ្រោះ ទ្រង់​យាង​មក​ពី​ស្ថាន​នោះ​ឯង'),
  ('km', 163, 'ទំនុកដំកើង 133:1', 'មើល ដែល​បង​ប្អូន​នៅ​មូល​ជា​មួយ​គ្នា ដោយ​ចិត្ត​ព្រម​ព្រៀង នោះ​ជា​ការ​ល្អ ហើយ​សម​គួរ​យ៉ាង​ណា​ទៅ'),
  ('km', 164, 'កាឡាទី 6:9', 'កុំ​ឲ្យ​យើង​ណាយ​ចិត្ត​នឹង​ធ្វើ​ការ​ល្អ​ឡើយ ដ្បិត​បើ​មិន​រសាយ​ចិត្ត​ទេ នោះ​ដល់​កំណត់ យើង​នឹង​ច្រូត​បាន​ហើយ'),
  ('km', 165, 'ធីម៉ូថេ​ទី​២ 4:2', 'ចូរ​ឲ្យ​អ្នក​ផ្សាយ​ព្រះបន្ទូល​ចុះ ហើយ​ទទូច​ជំរុញ​ផង ទោះ​ត្រូវ​ពេល ឬ​ខុស​ក្តី ចូរ​រំឭក​គេ​ឲ្យ​ដឹង​ខ្លួន ព្រម​ទាំង​បន្ទោស ហើយ​កំឡា​ចិត្ត​គេ ដោយ​ចិត្ត​អត់ធ្មត់ និង​សេចក្តី​ប្រៀន​ប្រដៅ​គ្រប់​យ៉ាង'),
  ('km', 166, 'សុភាសិត 17:17', 'មិត្រ​សំឡាញ់​រមែង​ស្រឡាញ់​គ្នា​នៅ​គ្រប់​វេលា ឯ​បង​ប្អូន​ក៏​កើត​មក​សំរាប់​គ្រា​លំបាក​ដែរ។'),
  ('km', 167, 'អេភេសូ 5:16', 'ទាំង​លៃ​យក​ឱកាស​ឲ្យ​ទាន់​ពេល​ផង ពី​ព្រោះ​សម័យ​នេះ​អាក្រក់​ណាស់'),
  ('km', 168, 'ធីម៉ូថេ​ទី​២ 4:7', 'ខ្ញុំ​បាន​តយុទ្ធ​យ៉ាង​ល្អ ខ្ញុំ​បាន​រត់​ប្រណាំង​ជា​ស្រេច ខ្ញុំ​បាន​រក្សា​សេចក្តី​ជំនឿ​ទៅ​ហើយ'),
  ('km', 169, 'ម៉ាថាយ 18:20', 'ដ្បិត​កន្លែង​ណា​ដែល​មាន​២ឬ៣​អ្នក ប្រជុំ​ជា​មួយ​គ្នា ដោយ​នូវ​ឈ្មោះ​ខ្ញុំ នោះ​ខ្ញុំ​ក៏​នៅ​កណ្តាល​ចំណោម​អ្នក​ទាំង​នោះ​ដែរ។'),
  ('km', 170, 'កូឡូស 3:23', 'ហើយ​ការ​អ្វី​ដែល​ត្រូវ​ធ្វើ​ក៏​ដោយ ចូរ​ធ្វើ​ឲ្យ​អស់​ពី​ចិត្ត ទុក​ដូច​ជា​ធ្វើ​ថ្វាយ​ដល់​ព្រះអម្ចាស់ មិន​មែន​ដល់​មនុស្ស​ទេ'),
  ('km', 171, 'ហេព្រើរ 11:13', 'ពួក​អ្នក​ទាំង​នោះ​បាន​ស្លាប់​ក្នុង​សេចក្តី​ជំនឿ ឥត​ទទួល​សេចក្តី​ដែល​បាន​សន្យា​ទាំង​ប៉ុន្មាន​ទេ តែ​គេ​បាន​ឃើញ​ពី​ចំងាយ ហើយ​ក៏​ទទួល​គំនាប់​ដែរ ទាំង​យល់​ព្រម​ថា ខ្លួន​គេ​ជា​អ្នក​ដទៃ ដែល​គ្រាន់​តែ​សំណាក់នៅ​ផែនដី​ប៉ុណ្ណោះ'),
  ('km', 172, 'ថែស្សាឡូនីច​ទី​១ 5:18', 'ចូរ​អរ​ព្រះគុណ​ក្នុង​គ្រប់​ការ​ទាំង​អស់ ពី​ព្រោះ​ព្រះ​ទ្រង់​សព្វ​ព្រះហឫទ័យ​ឲ្យ​អ្នក​រាល់​គ្នា​ធ្វើ​យ៉ាង​ដូច្នោះ ដោយ​នូវ​ព្រះគ្រីស្ទយេស៊ូវ'),
  ('km', 173, 'ហេព្រើរ 12:1', 'ដូច្នេះ ដែល​មាន​ស្មរ​បន្ទាល់​១​ហ្វូង​ធំ​ម៉្លេះ នៅ​ព័ទ្ធ​ជុំវិញ​យើង នោះ​ត្រូវ​ឲ្យ​យើង​ចោល​អស់​ទាំង​បន្ទុក និង​អំពើ​បាប ដែល​រុំ​យើង​ជុំវិញ​ជា​ងាយ​ម៉្លេះ​នោះ​ចេញ ហើយ​ត្រូវ​រត់​ក្នុង​ទី​ប្រណាំង ដែល​នៅ​មុខ​យើង ដោយ​អំណត់'),
  ('km', 174, 'ធីម៉ូថេ​ទី​២ 3:16', 'គ្រប់​ទាំង​បទ​គម្ពីរ គឺ​ជា​ព្រះ​ទ្រង់​បាន​បញ្ចេញ​ព្រះវិញ្ញាណ​បណ្តាល​ឲ្យ​តែង​ទេ ក៏​មាន​ប្រយោជន៍​សំរាប់​ការ​បង្រៀន ការ​រំឭក​ឲ្យ​ដឹង​ខ្លួន ការ​ប្រដៅ​ដំរង់ និង​ការ​បង្ហាត់​ខាង​ឯ​សេចក្តី​សុចរិត'),
  ('km', 175, 'ពេត្រុស​ទី​១ 1:3', 'សូម​សរសើរ​ដល់​ព្រះ​ដ៏​ជា​ព្រះវរបិតា​នៃ​ព្រះយេស៊ូវគ្រីស្ទ ជា​ព្រះអម្ចាស់​នៃ​យើង​រាល់​គ្នា ដែល​ទ្រង់​បាន​បង្កើត​យើង​ឡើង​ជា​ថ្មី តាម​សេចក្តី​មេត្តាករុណា​ដ៏​ធំ​របស់​ទ្រង់ ដើម្បី​ឲ្យ​យើង​រាល់​គ្នា​បាន​សេចក្តី​សង្ឃឹម​ដ៏​រស់ ដោយសារ​ព្រះយេស៊ូវគ្រីស្ទ ទ្រង់​រស់​ពី​ស្លាប់​ឡើង​វិញ'),
  ('km', 176, 'យ៉ាកុប 1:22', 'ចូរ​ឲ្យ​អ្នក​រាល់​គ្នា​ប្រព្រឹត្ត​តាម​ព្រះបន្ទូល​ទៅ កុំ​ឲ្យ​គ្រាន់​តែ​ស្តាប់​ប៉ុណ្ណោះ ហើយ​បញ្ឆោត​ខ្លួន​វិញ​នោះ​ឡើយ'),
  ('km', 177, 'ពេត្រុស​ទី​១ 2:9', 'តែ​អ្នក​រាល់​គ្នា​ជា​ពូជ​ជ្រើសរើស ជា​ពួក​សង្ឃ​ហ្លួង ជា​សាសន៍​បរិសុទ្ធ ជា​រាស្ត្រ​ដ៏​ជា​កេរ្តិ៍អាករ​នៃ​ព្រះ ដើម្បី​ឲ្យ​អ្នក​រាល់​គ្នា​បាន​សំដែង​ចេញ ឲ្យ​ឃើញ​អស់​ទាំង​លក្ខណៈ​របស់​ព្រះ ដែល​ទ្រង់​បាន​ហៅ​អ្នក​រាល់​គ្នា​ចេញ​ពី​សេចក្តី​ងងឹត មក​ក្នុង​ពន្លឺ​អស្ចារ្យ​របស់​ទ្រង់'),
  ('km', 178, 'យ៉ាកុប 4:8', 'ត្រូវ​ចូល​ទៅ​ជិត​ព្រះ នោះ​ទ្រង់​នឹង​ចូល​មក​ជិត​អ្នក​រាល់​គ្នា​ដែរ ឱ​ពួក​មាន​បាប​អើយ ចូរ​លាង​ដៃ​ឲ្យ​ស្អាត​ចុះ ឱ​ពួក​អ្នក​មាន​ចិត្ត​២​អើយ ចូរ​សំអាត​ចិត្ត​ឡើង'),
  ('km', 179, 'ពេត្រុស​ទី​១ 2:11', 'ឱ​ពួក​ស្ងួនភ្ងា​អើយ ខ្ញុំ​ទូន្មាន​អ្នក​រាល់​គ្នា​ទុក​ដូច​ជា​ពួក​ប្រទេស​ក្រៅ ហើយ​ដូច​ជា​ពួក​អ្នក​ដែល​គ្រាន់​តែ​សំណាក់​នៅ​ថា ចូរ​ឲ្យ​អ្នក​រាល់​គ្នា​ចៀស​ពី​សេចក្តី​ប៉ងប្រាថ្នាខាង​សាច់​ឈាម ដែល​តយុទ្ធ​នឹង​ព្រលឹង​វិញ្ញាណ​ចេញ'),
  ('km', 180, 'ពេត្រុស​ទី​១ 3:15', 'ចូរ​ឲ្យ​តាំង​ព្រះគ្រីស្ទ​ឡើង ជា​បរិសុទ្ធ នៅ​ក្នុង​ចិត្ត​អ្នក​រាល់​គ្នា ទុក​ជា​ព្រះអម្ចាស់​ចុះ ហើយ​ឲ្យ​ប្រុង​ប្រៀប​ជានិច្ច ដោយ​សុភាព ហើយ​កោតខ្លាច ដើម្បី​នឹង​តប​ឆ្លើយ​ដល់​អ្នក​ណា​ដែល​សួរ​ពី​ហេតុ​នៃ​សេចក្តី​សង្ឃឹម​របស់​អ្នក​រាល់​គ្នា'),
  ('km', 181, 'វិវរណៈ 7:9', 'ក្រោយ​នោះ​មក ខ្ញុំ​ក្រឡេក​ទៅ​ឃើញ​មនុស្ស​១​ហ្វូង​យ៉ាង​ធំ ដែល​គ្មាន​អ្នក​ណា​អាច​នឹង​រាប់​បាន​ឡើយ គេ​មក​ពី​គ្រប់​ទាំង​សាសន៍ គ្រប់​ទាំង​ពូជ​មនុស្ស គ្រប់​ទាំង​គ្រួសារ ហើយ​គ្រប់​ទាំង​ភាសា ក៏​ឈរ​នៅ​មុខ​បល្ល័ង្ក និង​កូន​ចៀម ទាំង​ពាក់​អាវ​ស​វែង ហើយ​កាន់​ធាង​ចាក​នៅ​ដៃ'),
  ('km', 182, 'វិវរណៈ 21:5', 'ឯ​ព្រះអង្គ ដែល​គង់​លើ​បល្ល័ង្ក ទ្រង់​មាន​ព្រះបន្ទូល​ថា មើល អញ​ធ្វើ​ទាំង​អស់​ឡើង​ជា​ថ្មី រួច​ទ្រង់​មាន​ព្រះបន្ទូល​មក​ខ្ញុំ​ថា ចូរ​សរសេរ​ទុក​ចុះ ដ្បិត​ពាក្យ​ទាំង​នេះ​ពិត​ប្រាកដ ហើយ​គួរ​ជឿ'),
  ('km', 183, 'វិវរណៈ 22:20', 'ព្រះអង្គ ដែល​ធ្វើ​បន្ទាល់​ពី​សេចក្តី​ទាំង​នេះ ទ្រង់​មាន​ព្រះបន្ទូល​ថា អើ អញ​មក​ជា​ឆាប់។ អាម៉ែន ព្រះអម្ចាស់​យេស៊ូវ​អើយ សូម​យាង​មក។');
